

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_BlobDefaults(pybind11::module_& module);
void register_smoke_DartDeprecatedPosDefaults(pybind11::module_& module);
void register_smoke_DartDeprecatedPosDefaultsCustom(pybind11::module_& module);
void register_smoke_DefaultValues(pybind11::module_& module);
void register_smoke_DefaultValuesNullableStructWithDefaults(pybind11::module_& module);
void register_smoke_DefaultValuesStructWithDefaults(pybind11::module_& module);
void register_smoke_DefaultValuesStructWithEmptyDefaults(pybind11::module_& module);
void register_smoke_DefaultValuesStructWithSpecialDefaults(pybind11::module_& module);
void register_smoke_DefaultValuesStructWithTypedefDefaults(pybind11::module_& module);
void register_smoke_DefaultsWithFcStruct(pybind11::module_& module);
void register_smoke_FcStruct(pybind11::module_& module);
void register_smoke_ImmutableStructWithDefaults(pybind11::module_& module);
void register_smoke_JavaDeprecatedPosDefaults(pybind11::module_& module);
void register_smoke_JavaDeprecatedPosDefaultsCustom(pybind11::module_& module);
void register_smoke_PosDefaultStructWithCustomStructsFields(pybind11::module_& module);
void register_smoke_PosDefaultStructWithFieldUsingImmutableStruct(pybind11::module_& module);
void register_smoke_PosDefaultsWithDuration(pybind11::module_& module);
void register_smoke_PosDefaultsWithoutDefaults(pybind11::module_& module);
void register_smoke_SomeMutableCustomStructWithDefaults(pybind11::module_& module);
void register_smoke_StructWithAllDefaults(pybind11::module_& module);
void register_smoke_StructWithCollectionDefaults(pybind11::module_& module);
void register_smoke_StructWithInitializerDefaults(pybind11::module_& module);
void register_smoke_StructWithJavaPositionalDefaults(pybind11::module_& module);
void register_smoke_StructWithKotlinPositionalDefaults(pybind11::module_& module);
void register_smoke_StructWithNullableCollectionDefaults(pybind11::module_& module);
void register_smoke_StructWithSomeDefaults(pybind11::module_& module);
void register_smoke_TypesWithDefaults(pybind11::module_& module);
void register_smoke_TypesWithDefaultsImmutableStructWithCollections(pybind11::module_& module);
void register_smoke_TypesWithDefaultsImmutableStructWithDefaults(pybind11::module_& module);
void register_smoke_TypesWithDefaultsImmutableStructWithFieldConstructorAndCollections(pybind11::module_& module);
void register_smoke_TypesWithDefaultsImmutableStructWithFieldConstructorAndFieldUsingImmutableStruct(pybind11::module_& module);
void register_smoke_TypesWithDefaultsImmutableStructWithFieldConstructorAndNullableFieldUsingImmutableStruct(pybind11::module_& module);
void register_smoke_TypesWithDefaultsImmutableStructWithFieldUsingImmutableStruct(pybind11::module_& module);
void register_smoke_TypesWithDefaultsImmutableStructWithNullableFieldUsingImmutableStruct(pybind11::module_& module);
void register_smoke_TypesWithDefaultsSomeImmutableStructWithDefaults(pybind11::module_& module);
void register_smoke_TypesWithDefaultsStructWithDefaults(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_BlobDefaults(m);
    register_smoke_DartDeprecatedPosDefaults(m);
    register_smoke_DartDeprecatedPosDefaultsCustom(m);
    register_smoke_DefaultValues(m);
    register_smoke_DefaultValuesNullableStructWithDefaults(m);
    register_smoke_DefaultValuesStructWithDefaults(m);
    register_smoke_DefaultValuesStructWithEmptyDefaults(m);
    register_smoke_DefaultValuesStructWithSpecialDefaults(m);
    register_smoke_DefaultValuesStructWithTypedefDefaults(m);
    register_smoke_DefaultsWithFcStruct(m);
    register_smoke_FcStruct(m);
    register_smoke_ImmutableStructWithDefaults(m);
    register_smoke_JavaDeprecatedPosDefaults(m);
    register_smoke_JavaDeprecatedPosDefaultsCustom(m);
    register_smoke_PosDefaultStructWithCustomStructsFields(m);
    register_smoke_PosDefaultStructWithFieldUsingImmutableStruct(m);
    register_smoke_PosDefaultsWithDuration(m);
    register_smoke_PosDefaultsWithoutDefaults(m);
    register_smoke_SomeMutableCustomStructWithDefaults(m);
    register_smoke_StructWithAllDefaults(m);
    register_smoke_StructWithCollectionDefaults(m);
    register_smoke_StructWithInitializerDefaults(m);
    register_smoke_StructWithJavaPositionalDefaults(m);
    register_smoke_StructWithKotlinPositionalDefaults(m);
    register_smoke_StructWithNullableCollectionDefaults(m);
    register_smoke_StructWithSomeDefaults(m);
    register_smoke_TypesWithDefaults(m);
    register_smoke_TypesWithDefaultsImmutableStructWithCollections(m);
    register_smoke_TypesWithDefaultsImmutableStructWithDefaults(m);
    register_smoke_TypesWithDefaultsImmutableStructWithFieldConstructorAndCollections(m);
    register_smoke_TypesWithDefaultsImmutableStructWithFieldConstructorAndFieldUsingImmutableStruct(m);
    register_smoke_TypesWithDefaultsImmutableStructWithFieldConstructorAndNullableFieldUsingImmutableStruct(m);
    register_smoke_TypesWithDefaultsImmutableStructWithFieldUsingImmutableStruct(m);
    register_smoke_TypesWithDefaultsImmutableStructWithNullableFieldUsingImmutableStruct(m);
    register_smoke_TypesWithDefaultsSomeImmutableStructWithDefaults(m);
    register_smoke_TypesWithDefaultsStructWithDefaults(m);
}
