

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_BlobDefaults(py::module_& module);
void register_DartDeprecatedPosDefaults(py::module_& module);
void register_DartDeprecatedPosDefaultsCustom(py::module_& module);
void register_DefaultValues(py::module_& module);
void register_DefaultsWithFcStruct(py::module_& module);
void register_FcStruct(py::module_& module);
void register_ImmutableStructWithDefaults(py::module_& module);
void register_JavaDeprecatedPosDefaults(py::module_& module);
void register_JavaDeprecatedPosDefaultsCustom(py::module_& module);
void register_PosDefaultStructWithCustomStructsFields(py::module_& module);
void register_PosDefaultStructWithFieldUsingImmutableStruct(py::module_& module);
void register_PosDefaultsWithDuration(py::module_& module);
void register_PosDefaultsWithoutDefaults(py::module_& module);
void register_SomeMutableCustomStructWithDefaults(py::module_& module);
void register_StructWithAllDefaults(py::module_& module);
void register_StructWithCollectionDefaults(py::module_& module);
void register_StructWithInitializerDefaults(py::module_& module);
void register_StructWithJavaPositionalDefaults(py::module_& module);
void register_StructWithKotlinPositionalDefaults(py::module_& module);
void register_StructWithNullableCollectionDefaults(py::module_& module);
void register_StructWithSomeDefaults(py::module_& module);
void register_TypesWithDefaults(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_BlobDefaults(m);
    register_DartDeprecatedPosDefaults(m);
    register_DartDeprecatedPosDefaultsCustom(m);
    register_DefaultValues(m);
    register_DefaultsWithFcStruct(m);
    register_FcStruct(m);
    register_ImmutableStructWithDefaults(m);
    register_JavaDeprecatedPosDefaults(m);
    register_JavaDeprecatedPosDefaultsCustom(m);
    register_PosDefaultStructWithCustomStructsFields(m);
    register_PosDefaultStructWithFieldUsingImmutableStruct(m);
    register_PosDefaultsWithDuration(m);
    register_PosDefaultsWithoutDefaults(m);
    register_SomeMutableCustomStructWithDefaults(m);
    register_StructWithAllDefaults(m);
    register_StructWithCollectionDefaults(m);
    register_StructWithInitializerDefaults(m);
    register_StructWithJavaPositionalDefaults(m);
    register_StructWithKotlinPositionalDefaults(m);
    register_StructWithNullableCollectionDefaults(m);
    register_StructWithSomeDefaults(m);
    register_TypesWithDefaults(m);
}
