

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_BlobDefaults(pybind11::module_& module);
void register_DartDeprecatedPosDefaults(pybind11::module_& module);
void register_DartDeprecatedPosDefaultsCustom(pybind11::module_& module);
void register_DefaultValues(pybind11::module_& module);
void register_DefaultValuesNullableStructWithDefaults(pybind11::module_& module);
void register_DefaultValuesStructWithDefaults(pybind11::module_& module);
void register_DefaultValuesStructWithEmptyDefaults(pybind11::module_& module);
void register_DefaultValuesStructWithSpecialDefaults(pybind11::module_& module);
void register_DefaultValuesStructWithTypedefDefaults(pybind11::module_& module);
void register_DefaultsWithFcStruct(pybind11::module_& module);
void register_FcStruct(pybind11::module_& module);
void register_ImmutableStructWithDefaults(pybind11::module_& module);
void register_JavaDeprecatedPosDefaults(pybind11::module_& module);
void register_JavaDeprecatedPosDefaultsCustom(pybind11::module_& module);
void register_PosDefaultStructWithCustomStructsFields(pybind11::module_& module);
void register_PosDefaultStructWithFieldUsingImmutableStruct(pybind11::module_& module);
void register_PosDefaultsWithDuration(pybind11::module_& module);
void register_PosDefaultsWithoutDefaults(pybind11::module_& module);
void register_SomeMutableCustomStructWithDefaults(pybind11::module_& module);
void register_StructWithAllDefaults(pybind11::module_& module);
void register_StructWithCollectionDefaults(pybind11::module_& module);
void register_StructWithInitializerDefaults(pybind11::module_& module);
void register_StructWithJavaPositionalDefaults(pybind11::module_& module);
void register_StructWithKotlinPositionalDefaults(pybind11::module_& module);
void register_StructWithNullableCollectionDefaults(pybind11::module_& module);
void register_StructWithSomeDefaults(pybind11::module_& module);
void register_TypesWithDefaults(pybind11::module_& module);
void register_TypesWithDefaultsImmutableStructWithCollections(pybind11::module_& module);
void register_TypesWithDefaultsImmutableStructWithDefaults(pybind11::module_& module);
void register_TypesWithDefaultsImmutableStructWithFieldConstructorAndCollections(pybind11::module_& module);
void register_TypesWithDefaultsImmutableStructWithFieldConstructorAndFieldUsingImmutableStruct(pybind11::module_& module);
void register_TypesWithDefaultsImmutableStructWithFieldConstructorAndNullableFieldUsingImmutableStruct(pybind11::module_& module);
void register_TypesWithDefaultsImmutableStructWithFieldUsingImmutableStruct(pybind11::module_& module);
void register_TypesWithDefaultsImmutableStructWithNullableFieldUsingImmutableStruct(pybind11::module_& module);
void register_TypesWithDefaultsSomeImmutableStructWithDefaults(pybind11::module_& module);
void register_TypesWithDefaultsStructWithDefaults(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_BlobDefaults(m);
    register_DartDeprecatedPosDefaults(m);
    register_DartDeprecatedPosDefaultsCustom(m);
    register_DefaultValues(m);
    register_DefaultValuesNullableStructWithDefaults(m);
    register_DefaultValuesStructWithDefaults(m);
    register_DefaultValuesStructWithEmptyDefaults(m);
    register_DefaultValuesStructWithSpecialDefaults(m);
    register_DefaultValuesStructWithTypedefDefaults(m);
    register_DefaultsWithFcStruct(m);
    register_FcStruct(m);
    register_ImmutableStructWithDefaults(m);
    register_JavaDeprecatedPosDefaults(m);
    register_JavaDeprecatedPosDefaultsCustom(m);
    register_PosDefaultStructWithCustomStructsFields(m);
    register_PosDefaultStructWithFieldUsingImmutableStruct(m);
    register_PosDefaultsWithDuration(m);
    register_PosDefaultsWithoutDefaults(m);
    register_SomeMutableCustomStructWithDefaults(m);
    register_StructWithAllDefaults(m);
    register_StructWithCollectionDefaults(m);
    register_StructWithInitializerDefaults(m);
    register_StructWithJavaPositionalDefaults(m);
    register_StructWithKotlinPositionalDefaults(m);
    register_StructWithNullableCollectionDefaults(m);
    register_StructWithSomeDefaults(m);
    register_TypesWithDefaults(m);
    register_TypesWithDefaultsImmutableStructWithCollections(m);
    register_TypesWithDefaultsImmutableStructWithDefaults(m);
    register_TypesWithDefaultsImmutableStructWithFieldConstructorAndCollections(m);
    register_TypesWithDefaultsImmutableStructWithFieldConstructorAndFieldUsingImmutableStruct(m);
    register_TypesWithDefaultsImmutableStructWithFieldConstructorAndNullableFieldUsingImmutableStruct(m);
    register_TypesWithDefaultsImmutableStructWithFieldUsingImmutableStruct(m);
    register_TypesWithDefaultsImmutableStructWithNullableFieldUsingImmutableStruct(m);
    register_TypesWithDefaultsSomeImmutableStructWithDefaults(m);
    register_TypesWithDefaultsStructWithDefaults(m);
}
