

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_AttributesClass(py::module_& module);
void register_AttributesCrashError(py::module_& module);
void register_AttributesEnum(py::module_& module);
void register_AttributesInterface(py::module_& module);
void register_AttributesStruct(py::module_& module);
void register_AttributesWithComments(py::module_& module);
void register_AttributesWithDeprecated(py::module_& module);
void register_MultipleAttributesCpp(py::module_& module);
void register_MultipleAttributesDart(py::module_& module);
void register_MultipleAttributesJava(py::module_& module);
void register_MultipleAttributesKotlin(py::module_& module);
void register_MultipleAttributesSwift(py::module_& module);
void register_SpecialAttributes(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_AttributesClass(m);
    register_AttributesCrashError(m);
    register_AttributesEnum(m);
    register_AttributesInterface(m);
    register_AttributesStruct(m);
    register_AttributesWithComments(m);
    register_AttributesWithDeprecated(m);
    register_MultipleAttributesCpp(m);
    register_MultipleAttributesDart(m);
    register_MultipleAttributesJava(m);
    register_MultipleAttributesKotlin(m);
    register_MultipleAttributesSwift(m);
    register_SpecialAttributes(m);
}
