

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_another_SomeCoolClassType(pybind11::module_& module);
void register_smoke_ParentClass(pybind11::module_& module);
void register_smoke_ParentNarrowOne(pybind11::module_& module);
void register_smoke_FirstParentIsClassClass(pybind11::module_& module);
void register_smoke_ParentInterface(pybind11::module_& module);
void register_smoke_FirstParentIsInterfaceClass(pybind11::module_& module);
void register_smoke_FirstParentIsInterfaceInterface(pybind11::module_& module);
void register_smoke_ParentNarrowTwo(pybind11::module_& module);
void register_smoke_FirstParentIsNarrowClass(pybind11::module_& module);
void register_smoke_FirstParentIsNarrowInterface(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_another_SomeCoolClassType(m);
    register_smoke_ParentClass(m);
    register_smoke_ParentNarrowOne(m);
    register_smoke_FirstParentIsClassClass(m);
    register_smoke_ParentInterface(m);
    register_smoke_FirstParentIsInterfaceClass(m);
    register_smoke_FirstParentIsInterfaceInterface(m);
    register_smoke_ParentNarrowTwo(m);
    register_smoke_FirstParentIsNarrowClass(m);
    register_smoke_FirstParentIsNarrowInterface(m);
}
