

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_FirstParentIsClassClass(py::module_& module);
void register_FirstParentIsInterfaceClass(py::module_& module);
void register_FirstParentIsInterfaceInterface(py::module_& module);
void register_FirstParentIsNarrowClass(py::module_& module);
void register_FirstParentIsNarrowInterface(py::module_& module);
void register_ParentClass(py::module_& module);
void register_ParentInterface(py::module_& module);
void register_ParentNarrowOne(py::module_& module);
void register_ParentNarrowTwo(py::module_& module);
void register_SomeCoolClassType(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_FirstParentIsClassClass(m);
    register_FirstParentIsInterfaceClass(m);
    register_FirstParentIsInterfaceInterface(m);
    register_FirstParentIsNarrowClass(m);
    register_FirstParentIsNarrowInterface(m);
    register_ParentClass(m);
    register_ParentInterface(m);
    register_ParentNarrowOne(m);
    register_ParentNarrowTwo(m);
    register_SomeCoolClassType(m);
}
