#!/bin/bash -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"
REPO_ROOT=$(cd "${SCRIPT_DIR}/../.." && pwd)
BUILD_DIR=${REPO_ROOT}/build-functional-js

USAGE=$(cat <<EOF
$0 [options]
    --publish    Build and publish Gluecodium locally and use it for code generation
    --help       Print this message
EOF
)

while [[ $# -gt 0 ]]; do
    case "$1" in
        --publish)
            publish_local
            shift
            ;;
        --help)
            echo "$USAGE"
            exit 0
            ;;
        *)
            echo "$USAGE" >&2
            exit 1
            ;;
    esac
done

rm -rf -- "${BUILD_DIR}"

export GLUECODIUM_PATH="${REPO_ROOT}"

emcmake cmake \
    -S "${REPO_ROOT}/functional-tests" \
    -B "${BUILD_DIR}" \
    -G Ninja \
    -DGLUECODIUM_GENERATORS_DEFAULT="cpp;js" \
    -DFUNCTIONAL_BUILD_JS_TESTS=ON

cmake --build "${BUILD_DIR}" --target functional_bindings_js
ctest --test-dir "${BUILD_DIR}" --output-on-failure -R unit_tests_javascript