

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_example_FooBar(pybind11::module_& module);
void register_smoke_Errors(pybind11::module_& module);
void register_smoke_ErrorsExternal(pybind11::module_& module);
void register_smoke_ErrorsExternalErrors(pybind11::module_& module);
void register_smoke_ErrorsInterface(pybind11::module_& module);
void register_smoke_ErrorsInterfaceExternal(pybind11::module_& module);
void register_smoke_ErrorsInterfaceExternalErrors(pybind11::module_& module);
void register_smoke_ErrorsInterfaceInternal(pybind11::module_& module);
void register_smoke_ErrorsInterfaceInternalError(pybind11::module_& module);
void register_smoke_ErrorsInternal(pybind11::module_& module);
void register_smoke_ErrorsInternalErrorCode(pybind11::module_& module);
void register_smoke_Payload(pybind11::module_& module);
void register_smoke_SomeTypeCollection(pybind11::module_& module);
void register_smoke_SomeTypeCollectionSome(pybind11::module_& module);
void register_smoke_SomeTypeCollectionSomeTypeCollectionError(pybind11::module_& module);
void register_smoke_UseTcException(pybind11::module_& module);
void register_smoke_WithPayloadError(pybind11::module_& module);
void register_smoke_WithStringError(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_example_FooBar(m);
    register_smoke_Errors(m);
    register_smoke_ErrorsExternal(m);
    register_smoke_ErrorsExternalErrors(m);
    register_smoke_ErrorsInterface(m);
    register_smoke_ErrorsInterfaceExternal(m);
    register_smoke_ErrorsInterfaceExternalErrors(m);
    register_smoke_ErrorsInterfaceInternal(m);
    register_smoke_ErrorsInterfaceInternalError(m);
    register_smoke_ErrorsInternal(m);
    register_smoke_ErrorsInternalErrorCode(m);
    register_smoke_Payload(m);
    register_smoke_SomeTypeCollection(m);
    register_smoke_SomeTypeCollectionSome(m);
    register_smoke_SomeTypeCollectionSomeTypeCollectionError(m);
    register_smoke_UseTcException(m);
    register_smoke_WithPayloadError(m);
    register_smoke_WithStringError(m);
}
