

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-top-level-element register_* functions generated by Gluecodium.
// Each top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this function
// registers the top-level type AND all nested types using nested py::class_ scopes. This module
// entry point aggregates them into a single CPython extension module. The `pybind11::` prefix
// is used here because the `py` namespace alias is introduced further below (after these
// declarations).
void register_example_FooBar(pybind11::module_& module);
void register_smoke_Errors(pybind11::module_& module);
void register_smoke_ErrorsInterface(pybind11::module_& module);
void register_smoke_Payload(pybind11::module_& module);
void register_smoke_SomeTypeCollection(pybind11::module_& module);
void register_smoke_UseTcException(pybind11::module_& module);
void register_smoke_WithPayloadError(pybind11::module_& module);
void register_smoke_WithStringError(pybind11::module_& module);
void register_smoke__SomeInternalEnum(pybind11::module_& module);
void register_smoke__SomethingBadHappenedError(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_example_FooBar(m);
    register_smoke_Errors(m);
    register_smoke_ErrorsInterface(m);
    register_smoke_Payload(m);
    register_smoke_SomeTypeCollection(m);
    register_smoke_UseTcException(m);
    register_smoke_WithPayloadError(m);
    register_smoke_WithStringError(m);
    register_smoke__SomeInternalEnum(m);
    register_smoke__SomethingBadHappenedError(m);
}
