

#include <Python.h>
#include <pybind11/pybind11.h>
#include <pybind11/functional.h>
#include <pybind11/stl.h>
#include <pybind11/chrono.h>
#include "_wrapper_cache.h"
#include "_return_caster.h"
#include "_generic_caster.h"

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;
#include "smoke/Payload.h"


void register_smoke_WithPayloadError(py::module_& module) {
    // Import the Python exception class generated by PythonException.mustache so
    // that exceptions raised by the Return<T, Error> type caster are instances of
    // the Python class (not a separate native py::exception type). This ensures
    // pytest.raises() catches them correctly.
    static py::object py_exc =
        py::module_::import("smoke.WithPayloadError").attr("WithPayloadError");
    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const ::smoke::Payload& e) {
            const auto message = pybind11::detail::ReturnErrorToString<::smoke::Payload>::convert(e);
            PyErr_SetString(py_exc.ptr(), message.c_str());
        }
    });
    pybind11::detail::registerReturnError<::smoke::Payload>(py_exc.ptr());
}

