

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_Annotations(py::module_& module);
void register_OuterInternalEnum(py::module_& module);
void register_OuterInternalError(py::module_& module);
void register_OuterInternalInterface(py::module_& module);
void register_OuterInternalStruct(py::module_& module);
void register_OuterPublicClazz(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_Annotations(m);
    register_OuterInternalEnum(m);
    register_OuterInternalError(m);
    register_OuterInternalInterface(m);
    register_OuterInternalStruct(m);
    register_OuterPublicClazz(m);
}
