

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_Annotations(pybind11::module_& module);
void register_smoke_OuterInternalEnum(pybind11::module_& module);
void register_smoke_OuterInternalError(pybind11::module_& module);
void register_smoke_OuterInternalInterface(pybind11::module_& module);
void register_smoke_OuterInternalStruct(pybind11::module_& module);
void register_smoke_OuterPublicClazz(pybind11::module_& module);
void register_smoke_OuterPublicClazzInnerInternalClazz(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_Annotations(m);
    register_smoke_OuterInternalEnum(m);
    register_smoke_OuterInternalError(m);
    register_smoke_OuterInternalInterface(m);
    register_smoke_OuterInternalStruct(m);
    register_smoke_OuterPublicClazz(m);
    register_smoke_OuterPublicClazzInnerInternalClazz(m);
}
