

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_AliasError(py::module_& module);
void register_EnumOptionSet(py::module_& module);
void register_EnumOptionSetComments(py::module_& module);
void register_EnumStartsWithOne(py::module_& module);
void register_EnumWithAccessibleValues(py::module_& module);
void register_EnumWithAlias(py::module_& module);
void register_EnumWithAliasWithDeprecated(py::module_& module);
void register_EnumWithToStringHelper(py::module_& module);
void register_Enums(py::module_& module);
void register_EnumsInTypeCollection(py::module_& module);
void register_EnumsInTypeCollectionInterface(py::module_& module);
void register_UseEnumOptionSet(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_AliasError(m);
    register_EnumOptionSet(m);
    register_EnumOptionSetComments(m);
    register_EnumStartsWithOne(m);
    register_EnumWithAccessibleValues(m);
    register_EnumWithAlias(m);
    register_EnumWithAliasWithDeprecated(m);
    register_EnumWithToStringHelper(m);
    register_Enums(m);
    register_EnumsInTypeCollection(m);
    register_EnumsInTypeCollectionInterface(m);
    register_UseEnumOptionSet(m);
}
