

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-top-level-element register_* functions generated by Gluecodium.
// Each top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this function
// registers the top-level type AND all nested types using nested py::class_ scopes. This module
// entry point aggregates them into a single CPython extension module. The `pybind11::` prefix
// is used here because the `py` namespace alias is introduced further below (after these
// declarations).
void register_smoke_AliasError(pybind11::module_& module);
void register_smoke_EnumOptionSet(pybind11::module_& module);
void register_smoke_EnumOptionSetComments(pybind11::module_& module);
void register_smoke_EnumStartsWithOne(pybind11::module_& module);
void register_smoke_EnumWithAccessibleValues(pybind11::module_& module);
void register_smoke_EnumWithAlias(pybind11::module_& module);
void register_smoke_EnumWithAliasWithDeprecated(pybind11::module_& module);
void register_smoke_EnumWithToStringHelper(pybind11::module_& module);
void register_smoke_Enums(pybind11::module_& module);
void register_smoke_EnumsInTypeCollection(pybind11::module_& module);
void register_smoke_EnumsInTypeCollectionInterface(pybind11::module_& module);
void register_smoke_UseEnumOptionSet(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_AliasError(m);
    register_smoke_EnumOptionSet(m);
    register_smoke_EnumOptionSetComments(m);
    register_smoke_EnumStartsWithOne(m);
    register_smoke_EnumWithAccessibleValues(m);
    register_smoke_EnumWithAlias(m);
    register_smoke_EnumWithAliasWithDeprecated(m);
    register_smoke_EnumWithToStringHelper(m);
    register_smoke_Enums(m);
    register_smoke_EnumsInTypeCollection(m);
    register_smoke_EnumsInTypeCollectionInterface(m);
    register_smoke_UseEnumOptionSet(m);
}
