

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_ClassWithOverloads(py::module_& module);
void register_CompressionState(py::module_& module);
void register_Currency(py::module_& module);
void register_Currency(py::module_& module);
void register_DartColor(py::module_& module);
void register_DartExternalCtor(py::module_& module);
void register_DartSeason(py::module_& module);
void register_DateInterval(py::module_& module);
void register_DurationExternal(py::module_& module);
void register_Enums(py::module_& module);
void register_ExternalClass(py::module_& module);
void register_ExternalDartConstants(py::module_& module);
void register_ExternalInterface(py::module_& module);
void register_ExternalMarkedAsSerializable(py::module_& module);
void register_ExternalMarkedAsSerializable(py::module_& module);
void register_ExternalTypeInTypesCollection(py::module_& module);
void register_ExternalWithNoFunctions(py::module_& module);
void register_JavaExternalCtor(py::module_& module);
void register_JavaExternalTypesStruct(py::module_& module);
void register_KotlinExternalTypesStruct(py::module_& module);
void register_Month(py::module_& module);
void register_Month(py::module_& module);
void register_Persistence(py::module_& module);
void register_PseudoColor(py::module_& module);
void register_Rectangle(py::module_& module);
void register_Season(py::module_& module);
void register_Season(py::module_& module);
void register_SerializableStructWithExternalField(py::module_& module);
void register_SerializableStructWithExternalField(py::module_& module);
void register_StandaloneExternalEnum(py::module_& module);
void register_StructWithOverloads(py::module_& module);
void register_Structs(py::module_& module);
void register_SwiftExternalCtor(py::module_& module);
void register_SwiftSeason(py::module_& module);
void register_SystemColor(py::module_& module);
void register_SystemColor(py::module_& module);
void register_TimeZone(py::module_& module);
void register_TimeZone(py::module_& module);
void register_UseCppExternalTypes(py::module_& module);
void register_UseDartExternalGenerics(py::module_& module);
void register_UseDartExternalTypes(py::module_& module);
void register_UseJavaExternalConst(py::module_& module);
void register_UseJavaExternalTypes(py::module_& module);
void register_UseKotlinExternalConst(py::module_& module);
void register_UseKotlinExternalTypes(py::module_& module);
void register_UseSwiftExternalTypes(py::module_& module);
void register_VeryBoolean(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_ClassWithOverloads(m);
    register_CompressionState(m);
    register_Currency(m);
    register_Currency(m);
    register_DartColor(m);
    register_DartExternalCtor(m);
    register_DartSeason(m);
    register_DateInterval(m);
    register_DurationExternal(m);
    register_Enums(m);
    register_ExternalClass(m);
    register_ExternalDartConstants(m);
    register_ExternalInterface(m);
    register_ExternalMarkedAsSerializable(m);
    register_ExternalMarkedAsSerializable(m);
    register_ExternalTypeInTypesCollection(m);
    register_ExternalWithNoFunctions(m);
    register_JavaExternalCtor(m);
    register_JavaExternalTypesStruct(m);
    register_KotlinExternalTypesStruct(m);
    register_Month(m);
    register_Month(m);
    register_Persistence(m);
    register_PseudoColor(m);
    register_Rectangle(m);
    register_Season(m);
    register_Season(m);
    register_SerializableStructWithExternalField(m);
    register_SerializableStructWithExternalField(m);
    register_StandaloneExternalEnum(m);
    register_StructWithOverloads(m);
    register_Structs(m);
    register_SwiftExternalCtor(m);
    register_SwiftSeason(m);
    register_SystemColor(m);
    register_SystemColor(m);
    register_TimeZone(m);
    register_TimeZone(m);
    register_UseCppExternalTypes(m);
    register_UseDartExternalGenerics(m);
    register_UseDartExternalTypes(m);
    register_UseJavaExternalConst(m);
    register_UseJavaExternalTypes(m);
    register_UseKotlinExternalConst(m);
    register_UseKotlinExternalTypes(m);
    register_UseSwiftExternalTypes(m);
    register_VeryBoolean(m);
}
