

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_ClassWithOverloads(pybind11::module_& module);
void register_CompressionState(pybind11::module_& module);
void register_Currency(pybind11::module_& module);
void register_DartColor(pybind11::module_& module);
void register_DartExternalCtor(pybind11::module_& module);
void register_DartSeason(pybind11::module_& module);
void register_DateInterval(pybind11::module_& module);
void register_DurationExternal(pybind11::module_& module);
void register_Enums(pybind11::module_& module);
void register_EnumsExternal_Enum(pybind11::module_& module);
void register_EnumsVeryExternalEnum(pybind11::module_& module);
void register_ExternalClass(pybind11::module_& module);
void register_ExternalClasssome_Enum(pybind11::module_& module);
void register_ExternalClasssome_Struct(pybind11::module_& module);
void register_ExternalDartConstants(pybind11::module_& module);
void register_ExternalInterface(pybind11::module_& module);
void register_ExternalInterfacesome_Enum(pybind11::module_& module);
void register_ExternalInterfacesome_Struct(pybind11::module_& module);
void register_ExternalMarkedAsSerializable(pybind11::module_& module);
void register_ExternalTypeInTypesCollection(pybind11::module_& module);
void register_ExternalTypeInTypesCollectionIntStruct(pybind11::module_& module);
void register_ExternalWithNoFunctions(pybind11::module_& module);
void register_JavaExternalCtor(pybind11::module_& module);
void register_JavaExternalTypesStruct(pybind11::module_& module);
void register_KotlinExternalTypesStruct(pybind11::module_& module);
void register_Month(pybind11::module_& module);
void register_Persistence(pybind11::module_& module);
void register_PseudoColor(pybind11::module_& module);
void register_Rectangle(pybind11::module_& module);
void register_Season(pybind11::module_& module);
void register_SerializableStructWithExternalField(pybind11::module_& module);
void register_StandaloneExternalEnum(pybind11::module_& module);
void register_StructWithOverloads(pybind11::module_& module);
void register_Structs(pybind11::module_& module);
void register_StructsAnotherExternalStruct(pybind11::module_& module);
void register_StructsExternalStruct(pybind11::module_& module);
void register_SwiftExternalCtor(pybind11::module_& module);
void register_SwiftSeason(pybind11::module_& module);
void register_SystemColor(pybind11::module_& module);
void register_TimeZone(pybind11::module_& module);
void register_UseCppExternalTypes(pybind11::module_& module);
void register_UseDartExternalGenerics(pybind11::module_& module);
void register_UseDartExternalTypes(pybind11::module_& module);
void register_UseJavaExternalConst(pybind11::module_& module);
void register_UseJavaExternalTypes(pybind11::module_& module);
void register_UseKotlinExternalConst(pybind11::module_& module);
void register_UseKotlinExternalTypes(pybind11::module_& module);
void register_UseSwiftExternalTypes(pybind11::module_& module);
void register_VeryBoolean(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_ClassWithOverloads(m);
    register_CompressionState(m);
    register_Currency(m);
    register_DartColor(m);
    register_DartExternalCtor(m);
    register_DartSeason(m);
    register_DateInterval(m);
    register_DurationExternal(m);
    register_Enums(m);
    register_EnumsExternal_Enum(m);
    register_EnumsVeryExternalEnum(m);
    register_ExternalClass(m);
    register_ExternalClasssome_Enum(m);
    register_ExternalClasssome_Struct(m);
    register_ExternalDartConstants(m);
    register_ExternalInterface(m);
    register_ExternalInterfacesome_Enum(m);
    register_ExternalInterfacesome_Struct(m);
    register_ExternalMarkedAsSerializable(m);
    register_ExternalTypeInTypesCollection(m);
    register_ExternalTypeInTypesCollectionIntStruct(m);
    register_ExternalWithNoFunctions(m);
    register_JavaExternalCtor(m);
    register_JavaExternalTypesStruct(m);
    register_KotlinExternalTypesStruct(m);
    register_Month(m);
    register_Persistence(m);
    register_PseudoColor(m);
    register_Rectangle(m);
    register_Season(m);
    register_SerializableStructWithExternalField(m);
    register_StandaloneExternalEnum(m);
    register_StructWithOverloads(m);
    register_Structs(m);
    register_StructsAnotherExternalStruct(m);
    register_StructsExternalStruct(m);
    register_SwiftExternalCtor(m);
    register_SwiftSeason(m);
    register_SystemColor(m);
    register_TimeZone(m);
    register_UseCppExternalTypes(m);
    register_UseDartExternalGenerics(m);
    register_UseDartExternalTypes(m);
    register_UseJavaExternalConst(m);
    register_UseJavaExternalTypes(m);
    register_UseKotlinExternalConst(m);
    register_UseKotlinExternalTypes(m);
    register_UseSwiftExternalTypes(m);
    register_VeryBoolean(m);
}
