

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_dontsmoke_ExternalMarkedAsSerializable(pybind11::module_& module);
void register_dontsmoke_SerializableStructWithExternalField(pybind11::module_& module);
void register_dontsmoke_UseCppExternalTypes(pybind11::module_& module);
void register_dontsmoke_UseJavaExternalTypes(pybind11::module_& module);
void register_kotlin_smoke_Currency(pybind11::module_& module);
void register_kotlin_smoke_ExternalMarkedAsSerializable(pybind11::module_& module);
void register_kotlin_smoke_KotlinExternalTypesStruct(pybind11::module_& module);
void register_kotlin_smoke_Month(pybind11::module_& module);
void register_kotlin_smoke_Season(pybind11::module_& module);
void register_kotlin_smoke_SerializableStructWithExternalField(pybind11::module_& module);
void register_kotlin_smoke_SystemColor(pybind11::module_& module);
void register_kotlin_smoke_TimeZone(pybind11::module_& module);
void register_kotlin_smoke_UseKotlinExternalConst(pybind11::module_& module);
void register_kotlin_smoke_UseKotlinExternalTypes(pybind11::module_& module);
void register_kotlin_smoke_VeryBoolean(pybind11::module_& module);
void register_smoke_ClassWithOverloads(pybind11::module_& module);
void register_smoke_CompressionState(pybind11::module_& module);
void register_smoke_Currency(pybind11::module_& module);
void register_smoke_DartColor(pybind11::module_& module);
void register_smoke_DartExternalCtor(pybind11::module_& module);
void register_smoke_DartSeason(pybind11::module_& module);
void register_smoke_DateInterval(pybind11::module_& module);
void register_smoke_DurationExternal(pybind11::module_& module);
void register_smoke_Enums(pybind11::module_& module);
void register_smoke_EnumsExternal_Enum(pybind11::module_& module);
void register_smoke_EnumsVeryExternalEnum(pybind11::module_& module);
void register_smoke_ExternalClass(pybind11::module_& module);
void register_smoke_ExternalClasssome_Enum(pybind11::module_& module);
void register_smoke_ExternalClasssome_Struct(pybind11::module_& module);
void register_smoke_ExternalDartConstants(pybind11::module_& module);
void register_smoke_ExternalInterface(pybind11::module_& module);
void register_smoke_ExternalInterfacesome_Enum(pybind11::module_& module);
void register_smoke_ExternalInterfacesome_Struct(pybind11::module_& module);
void register_smoke_ExternalTypeInTypesCollection(pybind11::module_& module);
void register_smoke_ExternalTypeInTypesCollectionIntStruct(pybind11::module_& module);
void register_smoke_ExternalWithNoFunctions(pybind11::module_& module);
void register_smoke_JavaExternalCtor(pybind11::module_& module);
void register_smoke_JavaExternalTypesStruct(pybind11::module_& module);
void register_smoke_Month(pybind11::module_& module);
void register_smoke_Persistence(pybind11::module_& module);
void register_smoke_PseudoColor(pybind11::module_& module);
void register_smoke_Rectangle(pybind11::module_& module);
void register_smoke_Season(pybind11::module_& module);
void register_smoke_StandaloneExternalEnum(pybind11::module_& module);
void register_smoke_StructWithOverloads(pybind11::module_& module);
void register_smoke_Structs(pybind11::module_& module);
void register_smoke_StructsAnotherExternalStruct(pybind11::module_& module);
void register_smoke_StructsExternalStruct(pybind11::module_& module);
void register_smoke_SwiftExternalCtor(pybind11::module_& module);
void register_smoke_SwiftSeason(pybind11::module_& module);
void register_smoke_SystemColor(pybind11::module_& module);
void register_smoke_TimeZone(pybind11::module_& module);
void register_smoke_UseDartExternalGenerics(pybind11::module_& module);
void register_smoke_UseDartExternalTypes(pybind11::module_& module);
void register_smoke_UseJavaExternalConst(pybind11::module_& module);
void register_smoke_UseSwiftExternalTypes(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_dontsmoke_ExternalMarkedAsSerializable(m);
    register_dontsmoke_SerializableStructWithExternalField(m);
    register_dontsmoke_UseCppExternalTypes(m);
    register_dontsmoke_UseJavaExternalTypes(m);
    register_kotlin_smoke_Currency(m);
    register_kotlin_smoke_ExternalMarkedAsSerializable(m);
    register_kotlin_smoke_KotlinExternalTypesStruct(m);
    register_kotlin_smoke_Month(m);
    register_kotlin_smoke_Season(m);
    register_kotlin_smoke_SerializableStructWithExternalField(m);
    register_kotlin_smoke_SystemColor(m);
    register_kotlin_smoke_TimeZone(m);
    register_kotlin_smoke_UseKotlinExternalConst(m);
    register_kotlin_smoke_UseKotlinExternalTypes(m);
    register_kotlin_smoke_VeryBoolean(m);
    register_smoke_ClassWithOverloads(m);
    register_smoke_CompressionState(m);
    register_smoke_Currency(m);
    register_smoke_DartColor(m);
    register_smoke_DartExternalCtor(m);
    register_smoke_DartSeason(m);
    register_smoke_DateInterval(m);
    register_smoke_DurationExternal(m);
    register_smoke_Enums(m);
    register_smoke_EnumsExternal_Enum(m);
    register_smoke_EnumsVeryExternalEnum(m);
    register_smoke_ExternalClass(m);
    register_smoke_ExternalClasssome_Enum(m);
    register_smoke_ExternalClasssome_Struct(m);
    register_smoke_ExternalDartConstants(m);
    register_smoke_ExternalInterface(m);
    register_smoke_ExternalInterfacesome_Enum(m);
    register_smoke_ExternalInterfacesome_Struct(m);
    register_smoke_ExternalTypeInTypesCollection(m);
    register_smoke_ExternalTypeInTypesCollectionIntStruct(m);
    register_smoke_ExternalWithNoFunctions(m);
    register_smoke_JavaExternalCtor(m);
    register_smoke_JavaExternalTypesStruct(m);
    register_smoke_Month(m);
    register_smoke_Persistence(m);
    register_smoke_PseudoColor(m);
    register_smoke_Rectangle(m);
    register_smoke_Season(m);
    register_smoke_StandaloneExternalEnum(m);
    register_smoke_StructWithOverloads(m);
    register_smoke_Structs(m);
    register_smoke_StructsAnotherExternalStruct(m);
    register_smoke_StructsExternalStruct(m);
    register_smoke_SwiftExternalCtor(m);
    register_smoke_SwiftSeason(m);
    register_smoke_SystemColor(m);
    register_smoke_TimeZone(m);
    register_smoke_UseDartExternalGenerics(m);
    register_smoke_UseDartExternalTypes(m);
    register_smoke_UseJavaExternalConst(m);
    register_smoke_UseSwiftExternalTypes(m);
}
