

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_Alphabet(pybind11::module_& module);
void register_smoke_LearnToRead(pybind11::module_& module);
void register_smoke_LearnToReadAgain(pybind11::module_& module);
void register_smoke_NameClashLists(pybind11::module_& module);
void register_smoke_bar_Alphabet(pybind11::module_& module);
void register_smoke_foo_Alphabet(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_Alphabet(m);
    register_smoke_LearnToRead(m);
    register_smoke_LearnToReadAgain(m);
    register_smoke_NameClashLists(m);
    register_smoke_bar_Alphabet(m);
    register_smoke_foo_Alphabet(m);
}
