

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_DartInternalClass(pybind11::module_& module);
void register_DartInternalClassEnabled(pybind11::module_& module);
void register_DartInternalClassRev(pybind11::module_& module);
void register_DartInternalClassSkipped(pybind11::module_& module);
void register_DartInternalElements(pybind11::module_& module);
void register_DartInternalElementsEnabled(pybind11::module_& module);
void register_DartInternalElementsRev(pybind11::module_& module);
void register_DartInternalElementsSkipped(pybind11::module_& module);
void register_DartPublicClass(pybind11::module_& module);
void register_DartPublicClassEnabled(pybind11::module_& module);
void register_DartPublicClassSkipped(pybind11::module_& module);
void register_DartPublicElements(pybind11::module_& module);
void register_DartPublicElementsEnabled(pybind11::module_& module);
void register_DartPublicElementsSkipped(pybind11::module_& module);
void register_JavaInternalClass(pybind11::module_& module);
void register_JavaInternalClassRev(pybind11::module_& module);
void register_JavaInternalProperty(pybind11::module_& module);
void register_JavaInternalPropertyRev(pybind11::module_& module);
void register_JavaPublicClass(pybind11::module_& module);
void register_JavaSwiftInternalClass(pybind11::module_& module);
void register_KotlinInternalClass(pybind11::module_& module);
void register_KotlinInternalClassRev(pybind11::module_& module);
void register_KotlinPublicClass(pybind11::module_& module);
void register_PlatformInternalInterface(pybind11::module_& module);
void register_SwiftInternalClass(pybind11::module_& module);
void register_SwiftInternalClassRev(pybind11::module_& module);
void register_SwiftPublicClass(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_DartInternalClass(m);
    register_DartInternalClassEnabled(m);
    register_DartInternalClassRev(m);
    register_DartInternalClassSkipped(m);
    register_DartInternalElements(m);
    register_DartInternalElementsEnabled(m);
    register_DartInternalElementsRev(m);
    register_DartInternalElementsSkipped(m);
    register_DartPublicClass(m);
    register_DartPublicClassEnabled(m);
    register_DartPublicClassSkipped(m);
    register_DartPublicElements(m);
    register_DartPublicElementsEnabled(m);
    register_DartPublicElementsSkipped(m);
    register_JavaInternalClass(m);
    register_JavaInternalClassRev(m);
    register_JavaInternalProperty(m);
    register_JavaInternalPropertyRev(m);
    register_JavaPublicClass(m);
    register_JavaSwiftInternalClass(m);
    register_KotlinInternalClass(m);
    register_KotlinInternalClassRev(m);
    register_KotlinPublicClass(m);
    register_PlatformInternalInterface(m);
    register_SwiftInternalClass(m);
    register_SwiftInternalClassRev(m);
    register_SwiftPublicClass(m);
}
