

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-top-level-element register_* functions generated by Gluecodium.
// Each top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this function
// registers the top-level type AND all nested types using nested py::class_ scopes. This module
// entry point aggregates them into a single CPython extension module. The `pybind11::` prefix
// is used here because the `py` namespace alias is introduced further below (after these
// declarations).
void register_smoke_DartInternalClass(pybind11::module_& module);
void register_smoke_DartInternalClassEnabled(pybind11::module_& module);
void register_smoke_DartInternalClassRev(pybind11::module_& module);
void register_smoke_DartInternalClassSkipped(pybind11::module_& module);
void register_smoke_DartInternalElements(pybind11::module_& module);
void register_smoke_DartInternalElementsEnabled(pybind11::module_& module);
void register_smoke_DartInternalElementsRev(pybind11::module_& module);
void register_smoke_DartInternalElementsSkipped(pybind11::module_& module);
void register_smoke_DartPublicElements(pybind11::module_& module);
void register_smoke_DartPublicElementsEnabled(pybind11::module_& module);
void register_smoke_DartPublicElementsSkipped(pybind11::module_& module);
void register_smoke_JavaInternalClass(pybind11::module_& module);
void register_smoke_JavaInternalClassRev(pybind11::module_& module);
void register_smoke_JavaInternalProperty(pybind11::module_& module);
void register_smoke_JavaInternalPropertyRev(pybind11::module_& module);
void register_smoke_JavaSwiftInternalClass(pybind11::module_& module);
void register_smoke_KotlinInternalClass(pybind11::module_& module);
void register_smoke_KotlinInternalClassRev(pybind11::module_& module);
void register_smoke_PlatformInternalInterface(pybind11::module_& module);
void register_smoke_SwiftInternalClass(pybind11::module_& module);
void register_smoke_SwiftInternalClassRev(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_DartInternalClass(m);
    register_smoke_DartInternalClassEnabled(m);
    register_smoke_DartInternalClassRev(m);
    register_smoke_DartInternalClassSkipped(m);
    register_smoke_DartInternalElements(m);
    register_smoke_DartInternalElementsEnabled(m);
    register_smoke_DartInternalElementsRev(m);
    register_smoke_DartInternalElementsSkipped(m);
    register_smoke_DartPublicElements(m);
    register_smoke_DartPublicElementsEnabled(m);
    register_smoke_DartPublicElementsSkipped(m);
    register_smoke_JavaInternalClass(m);
    register_smoke_JavaInternalClassRev(m);
    register_smoke_JavaInternalProperty(m);
    register_smoke_JavaInternalPropertyRev(m);
    register_smoke_JavaSwiftInternalClass(m);
    register_smoke_KotlinInternalClass(m);
    register_smoke_KotlinInternalClassRev(m);
    register_smoke_PlatformInternalInterface(m);
    register_smoke_SwiftInternalClass(m);
    register_smoke_SwiftInternalClassRev(m);
}
