

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_DartInternalClass(py::module_& module);
void register_DartInternalClassEnabled(py::module_& module);
void register_DartInternalClassRev(py::module_& module);
void register_DartInternalClassSkipped(py::module_& module);
void register_DartInternalElements(py::module_& module);
void register_DartInternalElementsEnabled(py::module_& module);
void register_DartInternalElementsRev(py::module_& module);
void register_DartInternalElementsSkipped(py::module_& module);
void register_DartPublicClass(py::module_& module);
void register_DartPublicClassEnabled(py::module_& module);
void register_DartPublicClassSkipped(py::module_& module);
void register_DartPublicElements(py::module_& module);
void register_DartPublicElementsEnabled(py::module_& module);
void register_DartPublicElementsSkipped(py::module_& module);
void register_JavaInternalClass(py::module_& module);
void register_JavaInternalClassRev(py::module_& module);
void register_JavaInternalProperty(py::module_& module);
void register_JavaInternalPropertyRev(py::module_& module);
void register_JavaPublicClass(py::module_& module);
void register_JavaSwiftInternalClass(py::module_& module);
void register_KotlinInternalClass(py::module_& module);
void register_KotlinInternalClassRev(py::module_& module);
void register_KotlinPublicClass(py::module_& module);
void register_PlatformInternalInterface(py::module_& module);
void register_SwiftInternalClass(py::module_& module);
void register_SwiftInternalClassRev(py::module_& module);
void register_SwiftPublicClass(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_DartInternalClass(m);
    register_DartInternalClassEnabled(m);
    register_DartInternalClassRev(m);
    register_DartInternalClassSkipped(m);
    register_DartInternalElements(m);
    register_DartInternalElementsEnabled(m);
    register_DartInternalElementsRev(m);
    register_DartInternalElementsSkipped(m);
    register_DartPublicClass(m);
    register_DartPublicClassEnabled(m);
    register_DartPublicClassSkipped(m);
    register_DartPublicElements(m);
    register_DartPublicElementsEnabled(m);
    register_DartPublicElementsSkipped(m);
    register_JavaInternalClass(m);
    register_JavaInternalClassRev(m);
    register_JavaInternalProperty(m);
    register_JavaInternalPropertyRev(m);
    register_JavaPublicClass(m);
    register_JavaSwiftInternalClass(m);
    register_KotlinInternalClass(m);
    register_KotlinInternalClassRev(m);
    register_KotlinPublicClass(m);
    register_PlatformInternalInterface(m);
    register_SwiftInternalClass(m);
    register_SwiftInternalClassRev(m);
    register_SwiftPublicClass(m);
}
