

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_CollectionConstants(pybind11::module_& module);
void register_Constants(pybind11::module_& module);
void register_ConstantsInterface(pybind11::module_& module);
void register_ConstantsInterfaceStateEnum(pybind11::module_& module);
void register_ConstantsSkipCpp(pybind11::module_& module);
void register_ConstantsStateEnum(pybind11::module_& module);
void register_CrossFileConstants(pybind11::module_& module);
void register_StructConstants(pybind11::module_& module);
void register_StructConstantsNestingStruct(pybind11::module_& module);
void register_StructConstantsSomeStruct(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_CollectionConstants(m);
    register_Constants(m);
    register_ConstantsInterface(m);
    register_ConstantsInterfaceStateEnum(m);
    register_ConstantsSkipCpp(m);
    register_ConstantsStateEnum(m);
    register_CrossFileConstants(m);
    register_StructConstants(m);
    register_StructConstantsNestingStruct(m);
    register_StructConstantsSomeStruct(m);
}
