

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_CollectionConstants(py::module_& module);
void register_Constants(py::module_& module);
void register_ConstantsInterface(py::module_& module);
void register_ConstantsSkipCpp(py::module_& module);
void register_CrossFileConstants(py::module_& module);
void register_StructConstants(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_CollectionConstants(m);
    register_Constants(m);
    register_ConstantsInterface(m);
    register_ConstantsSkipCpp(m);
    register_CrossFileConstants(m);
    register_StructConstants(m);
}
