

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_ClassWithDocRef(pybind11::module_& module);
void register_ClassWithStructWithSkipLambdaInPlatform(pybind11::module_& module);
void register_DontSmokeEnum(pybind11::module_& module);
void register_DummyStruct(pybind11::module_& module);
void register_EnableIfEnabled(pybind11::module_& module);
void register_EnableIfField(pybind11::module_& module);
void register_EnableIfSkipped(pybind11::module_& module);
void register_EnableIfTypesEnabled(pybind11::module_& module);
void register_EnableIfTypesSkipped(pybind11::module_& module);
void register_EnableTagsInDart(pybind11::module_& module);
void register_EnableTagsInJava(pybind11::module_& module);
void register_EnableTagsInKotlin(pybind11::module_& module);
void register_EnableTagsInSwift(pybind11::module_& module);
void register_FieldConstructorsSkipTag(pybind11::module_& module);
void register_InheritFromSkipped(pybind11::module_& module);
void register_SkipEnableConstants(pybind11::module_& module);
void register_SkipEnableParameters(pybind11::module_& module);
void register_SkipEnumeratorAutoTag(pybind11::module_& module);
void register_SkipEnumeratorExplicitTag(pybind11::module_& module);
void register_SkipField(pybind11::module_& module);
void register_SkipFieldConstructorsClash(pybind11::module_& module);
void register_SkipFieldInPlatform(pybind11::module_& module);
void register_SkipFieldInPlatformImmutable(pybind11::module_& module);
void register_SkipFunctions(pybind11::module_& module);
void register_SkipMixed(pybind11::module_& module);
void register_SkipOverloads(pybind11::module_& module);
void register_SkipOverloadsInDart(pybind11::module_& module);
void register_SkipPlatforms(pybind11::module_& module);
void register_SkipProxy(pybind11::module_& module);
void register_SkipSetter(pybind11::module_& module);
void register_SkipTagsInDart(pybind11::module_& module);
void register_SkipTagsInJava(pybind11::module_& module);
void register_SkipTagsInKotlin(pybind11::module_& module);
void register_SkipTagsInSwift(pybind11::module_& module);
void register_SkipTagsOnly(pybind11::module_& module);
void register_SkipTypes(pybind11::module_& module);
void register_SkipTypesTags(pybind11::module_& module);
void register_SkippedEverywhere(pybind11::module_& module);
void register_SkippedEverywhereEnum(pybind11::module_& module);
void register_SkippedFunctionClass(pybind11::module_& module);
void register_SomeSkippedClass(pybind11::module_& module);
void register_SomeSkippedEnum(pybind11::module_& module);
void register_SomeSkippedStruct(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_ClassWithDocRef(m);
    register_ClassWithStructWithSkipLambdaInPlatform(m);
    register_DontSmokeEnum(m);
    register_DummyStruct(m);
    register_EnableIfEnabled(m);
    register_EnableIfField(m);
    register_EnableIfSkipped(m);
    register_EnableIfTypesEnabled(m);
    register_EnableIfTypesSkipped(m);
    register_EnableTagsInDart(m);
    register_EnableTagsInJava(m);
    register_EnableTagsInKotlin(m);
    register_EnableTagsInSwift(m);
    register_FieldConstructorsSkipTag(m);
    register_InheritFromSkipped(m);
    register_SkipEnableConstants(m);
    register_SkipEnableParameters(m);
    register_SkipEnumeratorAutoTag(m);
    register_SkipEnumeratorExplicitTag(m);
    register_SkipField(m);
    register_SkipFieldConstructorsClash(m);
    register_SkipFieldInPlatform(m);
    register_SkipFieldInPlatformImmutable(m);
    register_SkipFunctions(m);
    register_SkipMixed(m);
    register_SkipOverloads(m);
    register_SkipOverloadsInDart(m);
    register_SkipPlatforms(m);
    register_SkipProxy(m);
    register_SkipSetter(m);
    register_SkipTagsInDart(m);
    register_SkipTagsInJava(m);
    register_SkipTagsInKotlin(m);
    register_SkipTagsInSwift(m);
    register_SkipTagsOnly(m);
    register_SkipTypes(m);
    register_SkipTypesTags(m);
    register_SkippedEverywhere(m);
    register_SkippedEverywhereEnum(m);
    register_SkippedFunctionClass(m);
    register_SomeSkippedClass(m);
    register_SomeSkippedEnum(m);
    register_SomeSkippedStruct(m);
}
