

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_dont_smoke_DontSmokeEnum(pybind11::module_& module);
void register_smoke_ClassWithDocRef(pybind11::module_& module);
void register_smoke_ClassWithStructWithSkipLambdaInPlatform(pybind11::module_& module);
void register_smoke_ClassWithStructWithSkipLambdaInPlatformSkipLambdaInPlatform(pybind11::module_& module);
void register_smoke_DummyStruct(pybind11::module_& module);
void register_smoke_EnableIfEnabled(pybind11::module_& module);
void register_smoke_EnableIfField(pybind11::module_& module);
void register_smoke_EnableIfSkipped(pybind11::module_& module);
void register_smoke_EnableIfTypesEnabled(pybind11::module_& module);
void register_smoke_EnableIfTypesEnabledEnableMe(pybind11::module_& module);
void register_smoke_EnableIfTypesEnabledEnableMeToo(pybind11::module_& module);
void register_smoke_EnableIfTypesSkipped(pybind11::module_& module);
void register_smoke_EnableTagsInDart(pybind11::module_& module);
void register_smoke_EnableTagsInJava(pybind11::module_& module);
void register_smoke_EnableTagsInKotlin(pybind11::module_& module);
void register_smoke_EnableTagsInSwift(pybind11::module_& module);
void register_smoke_FieldConstructorsSkipTag(pybind11::module_& module);
void register_smoke_SkipProxy(pybind11::module_& module);
void register_smoke_InheritFromSkipped(pybind11::module_& module);
void register_smoke_SkipEnableConstants(pybind11::module_& module);
void register_smoke_SkipEnableParameters(pybind11::module_& module);
void register_smoke_SkipEnumeratorAutoTag(pybind11::module_& module);
void register_smoke_SkipEnumeratorExplicitTag(pybind11::module_& module);
void register_smoke_SkipField(pybind11::module_& module);
void register_smoke_SkipFieldConstructorsClash(pybind11::module_& module);
void register_smoke_SkipFieldInPlatform(pybind11::module_& module);
void register_smoke_SkipFieldInPlatformImmutable(pybind11::module_& module);
void register_smoke_SkipFunctions(pybind11::module_& module);
void register_smoke_SkipMixed(pybind11::module_& module);
void register_smoke_SkipOverloads(pybind11::module_& module);
void register_smoke_SkipOverloadsInDart(pybind11::module_& module);
void register_smoke_SkipPlatforms(pybind11::module_& module);
void register_smoke_SkipSetter(pybind11::module_& module);
void register_smoke_SkipTagsInDart(pybind11::module_& module);
void register_smoke_SkipTagsInJava(pybind11::module_& module);
void register_smoke_SkipTagsInKotlin(pybind11::module_& module);
void register_smoke_SkipTagsInSwift(pybind11::module_& module);
void register_smoke_SkipTagsOnly(pybind11::module_& module);
void register_smoke_SkipTypes(pybind11::module_& module);
void register_smoke_SkipTypesNotInDart(pybind11::module_& module);
void register_smoke_SkipTypesNotInJava(pybind11::module_& module);
void register_smoke_SkipTypesNotInKotlin(pybind11::module_& module);
void register_smoke_SkipTypesNotInSwift(pybind11::module_& module);
void register_smoke_SkipTypesTags(pybind11::module_& module);
void register_smoke_SkippedEverywhere(pybind11::module_& module);
void register_smoke_SkippedEverywhereEnum(pybind11::module_& module);
void register_smoke_SkippedFunctionClass(pybind11::module_& module);
void register_smoke_SomeSkippedClass(pybind11::module_& module);
void register_smoke_SomeSkippedEnum(pybind11::module_& module);
void register_smoke_SomeSkippedStruct(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_dont_smoke_DontSmokeEnum(m);
    register_smoke_ClassWithDocRef(m);
    register_smoke_ClassWithStructWithSkipLambdaInPlatform(m);
    register_smoke_ClassWithStructWithSkipLambdaInPlatformSkipLambdaInPlatform(m);
    register_smoke_DummyStruct(m);
    register_smoke_EnableIfEnabled(m);
    register_smoke_EnableIfField(m);
    register_smoke_EnableIfSkipped(m);
    register_smoke_EnableIfTypesEnabled(m);
    register_smoke_EnableIfTypesEnabledEnableMe(m);
    register_smoke_EnableIfTypesEnabledEnableMeToo(m);
    register_smoke_EnableIfTypesSkipped(m);
    register_smoke_EnableTagsInDart(m);
    register_smoke_EnableTagsInJava(m);
    register_smoke_EnableTagsInKotlin(m);
    register_smoke_EnableTagsInSwift(m);
    register_smoke_FieldConstructorsSkipTag(m);
    register_smoke_SkipProxy(m);
    register_smoke_InheritFromSkipped(m);
    register_smoke_SkipEnableConstants(m);
    register_smoke_SkipEnableParameters(m);
    register_smoke_SkipEnumeratorAutoTag(m);
    register_smoke_SkipEnumeratorExplicitTag(m);
    register_smoke_SkipField(m);
    register_smoke_SkipFieldConstructorsClash(m);
    register_smoke_SkipFieldInPlatform(m);
    register_smoke_SkipFieldInPlatformImmutable(m);
    register_smoke_SkipFunctions(m);
    register_smoke_SkipMixed(m);
    register_smoke_SkipOverloads(m);
    register_smoke_SkipOverloadsInDart(m);
    register_smoke_SkipPlatforms(m);
    register_smoke_SkipSetter(m);
    register_smoke_SkipTagsInDart(m);
    register_smoke_SkipTagsInJava(m);
    register_smoke_SkipTagsInKotlin(m);
    register_smoke_SkipTagsInSwift(m);
    register_smoke_SkipTagsOnly(m);
    register_smoke_SkipTypes(m);
    register_smoke_SkipTypesNotInDart(m);
    register_smoke_SkipTypesNotInJava(m);
    register_smoke_SkipTypesNotInKotlin(m);
    register_smoke_SkipTypesNotInSwift(m);
    register_smoke_SkipTypesTags(m);
    register_smoke_SkippedEverywhere(m);
    register_smoke_SkippedEverywhereEnum(m);
    register_smoke_SkippedFunctionClass(m);
    register_smoke_SomeSkippedClass(m);
    register_smoke_SomeSkippedEnum(m);
    register_smoke_SomeSkippedStruct(m);
}
