

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_ClassWithDocRef(py::module_& module);
void register_ClassWithStructWithSkipLambdaInPlatform(py::module_& module);
void register_DontSmokeEnum(py::module_& module);
void register_DummyStruct(py::module_& module);
void register_EnableIfEnabled(py::module_& module);
void register_EnableIfField(py::module_& module);
void register_EnableIfSkipped(py::module_& module);
void register_EnableIfTypesEnabled(py::module_& module);
void register_EnableIfTypesSkipped(py::module_& module);
void register_EnableTagsInDart(py::module_& module);
void register_EnableTagsInJava(py::module_& module);
void register_EnableTagsInKotlin(py::module_& module);
void register_EnableTagsInSwift(py::module_& module);
void register_FieldConstructorsSkipTag(py::module_& module);
void register_InheritFromSkipped(py::module_& module);
void register_SkipEnableConstants(py::module_& module);
void register_SkipEnableParameters(py::module_& module);
void register_SkipEnumeratorAutoTag(py::module_& module);
void register_SkipEnumeratorExplicitTag(py::module_& module);
void register_SkipField(py::module_& module);
void register_SkipFieldConstructorsClash(py::module_& module);
void register_SkipFieldInPlatform(py::module_& module);
void register_SkipFieldInPlatformImmutable(py::module_& module);
void register_SkipFunctions(py::module_& module);
void register_SkipMixed(py::module_& module);
void register_SkipOverloads(py::module_& module);
void register_SkipOverloadsInDart(py::module_& module);
void register_SkipPlatforms(py::module_& module);
void register_SkipProxy(py::module_& module);
void register_SkipSetter(py::module_& module);
void register_SkipTagsInDart(py::module_& module);
void register_SkipTagsInJava(py::module_& module);
void register_SkipTagsInKotlin(py::module_& module);
void register_SkipTagsInSwift(py::module_& module);
void register_SkipTagsOnly(py::module_& module);
void register_SkipTypes(py::module_& module);
void register_SkipTypesTags(py::module_& module);
void register_SkippedEverywhere(py::module_& module);
void register_SkippedEverywhereEnum(py::module_& module);
void register_SkippedFunctionClass(py::module_& module);
void register_SomeSkippedClass(py::module_& module);
void register_SomeSkippedEnum(py::module_& module);
void register_SomeSkippedStruct(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_ClassWithDocRef(m);
    register_ClassWithStructWithSkipLambdaInPlatform(m);
    register_DontSmokeEnum(m);
    register_DummyStruct(m);
    register_EnableIfEnabled(m);
    register_EnableIfField(m);
    register_EnableIfSkipped(m);
    register_EnableIfTypesEnabled(m);
    register_EnableIfTypesSkipped(m);
    register_EnableTagsInDart(m);
    register_EnableTagsInJava(m);
    register_EnableTagsInKotlin(m);
    register_EnableTagsInSwift(m);
    register_FieldConstructorsSkipTag(m);
    register_InheritFromSkipped(m);
    register_SkipEnableConstants(m);
    register_SkipEnableParameters(m);
    register_SkipEnumeratorAutoTag(m);
    register_SkipEnumeratorExplicitTag(m);
    register_SkipField(m);
    register_SkipFieldConstructorsClash(m);
    register_SkipFieldInPlatform(m);
    register_SkipFieldInPlatformImmutable(m);
    register_SkipFunctions(m);
    register_SkipMixed(m);
    register_SkipOverloads(m);
    register_SkipOverloadsInDart(m);
    register_SkipPlatforms(m);
    register_SkipProxy(m);
    register_SkipSetter(m);
    register_SkipTagsInDart(m);
    register_SkipTagsInJava(m);
    register_SkipTagsInKotlin(m);
    register_SkipTagsInSwift(m);
    register_SkipTagsOnly(m);
    register_SkipTypes(m);
    register_SkipTypesTags(m);
    register_SkippedEverywhere(m);
    register_SkippedEverywhereEnum(m);
    register_SkippedFunctionClass(m);
    register_SomeSkippedClass(m);
    register_SomeSkippedEnum(m);
    register_SomeSkippedStruct(m);
}
