

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-top-level-element register_* functions generated by Gluecodium.
// Each top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this function
// registers the top-level type AND all nested types using nested py::class_ scopes. This module
// entry point aggregates them into a single CPython extension module. The `pybind11::` prefix
// is used here because the `py` namespace alias is introduced further below (after these
// declarations).
void register_smoke_FieldConstructorWithBothComments(pybind11::module_& module);
void register_smoke_FieldConstructorWithComment(pybind11::module_& module);
void register_smoke_FieldConstructorWithDeprecationAndComment(pybind11::module_& module);
void register_smoke_FieldConstructorWithDeprecationOnly(pybind11::module_& module);
void register_smoke_FieldConstructorWithExcluded(pybind11::module_& module);
void register_smoke_FieldConstructorWithExcludedOnly(pybind11::module_& module);
void register_smoke_FieldConstructorWithParentComment(pybind11::module_& module);
void register_smoke_FieldConstructorsAllDefaults(pybind11::module_& module);
void register_smoke_FieldConstructorsCppSkip(pybind11::module_& module);
void register_smoke_FieldConstructorsInternal(pybind11::module_& module);
void register_smoke_FieldConstructorsInternalFields(pybind11::module_& module);
void register_smoke_FieldConstructorsNullableTypes(pybind11::module_& module);
void register_smoke_FieldConstructorsParameterDefaults(pybind11::module_& module);
void register_smoke_FieldConstructorsPartialDefaults(pybind11::module_& module);
void register_smoke_FieldConstructorsSkipAllFields(pybind11::module_& module);
void register_smoke_FieldConstructorsSkipCpp(pybind11::module_& module);
void register_smoke_FieldConstructorsSkipDefault(pybind11::module_& module);
void register_smoke_FieldConstructorsWithLabels(pybind11::module_& module);
void register_smoke_FieldCustomConstructorsMix(pybind11::module_& module);
void register_smoke_ImmutableDefaultCtor(pybind11::module_& module);
void register_smoke_ImmutableNamelessCtor(pybind11::module_& module);
void register_smoke_ImmutableStructNoClash(pybind11::module_& module);
void register_smoke_ImmutableStructWithClash(pybind11::module_& module);
void register_smoke_MutableStructImmutableFields(pybind11::module_& module);
void register_smoke_MutableStructImmutableFieldsDefault(pybind11::module_& module);
void register_smoke_MutableStructImmutableFieldsNameless(pybind11::module_& module);
void register_smoke_MutableStructNoClash(pybind11::module_& module);
void register_smoke_OuterStructWithFieldConstructor(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_FieldConstructorWithBothComments(m);
    register_smoke_FieldConstructorWithComment(m);
    register_smoke_FieldConstructorWithDeprecationAndComment(m);
    register_smoke_FieldConstructorWithDeprecationOnly(m);
    register_smoke_FieldConstructorWithExcluded(m);
    register_smoke_FieldConstructorWithExcludedOnly(m);
    register_smoke_FieldConstructorWithParentComment(m);
    register_smoke_FieldConstructorsAllDefaults(m);
    register_smoke_FieldConstructorsCppSkip(m);
    register_smoke_FieldConstructorsInternal(m);
    register_smoke_FieldConstructorsInternalFields(m);
    register_smoke_FieldConstructorsNullableTypes(m);
    register_smoke_FieldConstructorsParameterDefaults(m);
    register_smoke_FieldConstructorsPartialDefaults(m);
    register_smoke_FieldConstructorsSkipAllFields(m);
    register_smoke_FieldConstructorsSkipCpp(m);
    register_smoke_FieldConstructorsSkipDefault(m);
    register_smoke_FieldConstructorsWithLabels(m);
    register_smoke_FieldCustomConstructorsMix(m);
    register_smoke_ImmutableDefaultCtor(m);
    register_smoke_ImmutableNamelessCtor(m);
    register_smoke_ImmutableStructNoClash(m);
    register_smoke_ImmutableStructWithClash(m);
    register_smoke_MutableStructImmutableFields(m);
    register_smoke_MutableStructImmutableFieldsDefault(m);
    register_smoke_MutableStructImmutableFieldsNameless(m);
    register_smoke_MutableStructNoClash(m);
    register_smoke_OuterStructWithFieldConstructor(m);
}
