

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_FieldConstructorWithBothComments(py::module_& module);
void register_FieldConstructorWithComment(py::module_& module);
void register_FieldConstructorWithDeprecationAndComment(py::module_& module);
void register_FieldConstructorWithDeprecationOnly(py::module_& module);
void register_FieldConstructorWithExcluded(py::module_& module);
void register_FieldConstructorWithExcludedOnly(py::module_& module);
void register_FieldConstructorWithParentComment(py::module_& module);
void register_FieldConstructorsAllDefaults(py::module_& module);
void register_FieldConstructorsCppSkip(py::module_& module);
void register_FieldConstructorsInternal(py::module_& module);
void register_FieldConstructorsInternalFields(py::module_& module);
void register_FieldConstructorsNullableTypes(py::module_& module);
void register_FieldConstructorsParameterDefaults(py::module_& module);
void register_FieldConstructorsPartialDefaults(py::module_& module);
void register_FieldConstructorsSkipAllFields(py::module_& module);
void register_FieldConstructorsSkipCpp(py::module_& module);
void register_FieldConstructorsSkipDefault(py::module_& module);
void register_FieldConstructorsWithLabels(py::module_& module);
void register_FieldCustomConstructorsMix(py::module_& module);
void register_ImmutableDefaultCtor(py::module_& module);
void register_ImmutableNamelessCtor(py::module_& module);
void register_ImmutableStructNoClash(py::module_& module);
void register_ImmutableStructWithClash(py::module_& module);
void register_MutableStructImmutableFields(py::module_& module);
void register_MutableStructImmutableFieldsDefault(py::module_& module);
void register_MutableStructImmutableFieldsNameless(py::module_& module);
void register_MutableStructNoClash(py::module_& module);
void register_OuterStructWithFieldConstructor(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_FieldConstructorWithBothComments(m);
    register_FieldConstructorWithComment(m);
    register_FieldConstructorWithDeprecationAndComment(m);
    register_FieldConstructorWithDeprecationOnly(m);
    register_FieldConstructorWithExcluded(m);
    register_FieldConstructorWithExcludedOnly(m);
    register_FieldConstructorWithParentComment(m);
    register_FieldConstructorsAllDefaults(m);
    register_FieldConstructorsCppSkip(m);
    register_FieldConstructorsInternal(m);
    register_FieldConstructorsInternalFields(m);
    register_FieldConstructorsNullableTypes(m);
    register_FieldConstructorsParameterDefaults(m);
    register_FieldConstructorsPartialDefaults(m);
    register_FieldConstructorsSkipAllFields(m);
    register_FieldConstructorsSkipCpp(m);
    register_FieldConstructorsSkipDefault(m);
    register_FieldConstructorsWithLabels(m);
    register_FieldCustomConstructorsMix(m);
    register_ImmutableDefaultCtor(m);
    register_ImmutableNamelessCtor(m);
    register_ImmutableStructNoClash(m);
    register_ImmutableStructWithClash(m);
    register_MutableStructImmutableFields(m);
    register_MutableStructImmutableFieldsDefault(m);
    register_MutableStructImmutableFieldsNameless(m);
    register_MutableStructNoClash(m);
    register_OuterStructWithFieldConstructor(m);
}
