

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_FieldConstructorWithBothComments(pybind11::module_& module);
void register_FieldConstructorWithComment(pybind11::module_& module);
void register_FieldConstructorWithDeprecationAndComment(pybind11::module_& module);
void register_FieldConstructorWithDeprecationOnly(pybind11::module_& module);
void register_FieldConstructorWithExcluded(pybind11::module_& module);
void register_FieldConstructorWithExcludedOnly(pybind11::module_& module);
void register_FieldConstructorWithParentComment(pybind11::module_& module);
void register_FieldConstructorsAllDefaults(pybind11::module_& module);
void register_FieldConstructorsCppSkip(pybind11::module_& module);
void register_FieldConstructorsInternal(pybind11::module_& module);
void register_FieldConstructorsInternalFields(pybind11::module_& module);
void register_FieldConstructorsNullableTypes(pybind11::module_& module);
void register_FieldConstructorsNullableTypesFoodType(pybind11::module_& module);
void register_FieldConstructorsNullableTypesStructWithParameters(pybind11::module_& module);
void register_FieldConstructorsParameterDefaults(pybind11::module_& module);
void register_FieldConstructorsPartialDefaults(pybind11::module_& module);
void register_FieldConstructorsSkipAllFields(pybind11::module_& module);
void register_FieldConstructorsSkipCpp(pybind11::module_& module);
void register_FieldConstructorsSkipDefault(pybind11::module_& module);
void register_FieldConstructorsWithLabels(pybind11::module_& module);
void register_FieldCustomConstructorsMix(pybind11::module_& module);
void register_ImmutableDefaultCtor(pybind11::module_& module);
void register_ImmutableNamelessCtor(pybind11::module_& module);
void register_ImmutableStructNoClash(pybind11::module_& module);
void register_ImmutableStructWithClash(pybind11::module_& module);
void register_MutableStructImmutableFields(pybind11::module_& module);
void register_MutableStructImmutableFieldsDefault(pybind11::module_& module);
void register_MutableStructImmutableFieldsNameless(pybind11::module_& module);
void register_MutableStructNoClash(pybind11::module_& module);
void register_OuterStructWithFieldConstructor(pybind11::module_& module);
void register_OuterStructWithFieldConstructorInnerStructWithDefaults(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_FieldConstructorWithBothComments(m);
    register_FieldConstructorWithComment(m);
    register_FieldConstructorWithDeprecationAndComment(m);
    register_FieldConstructorWithDeprecationOnly(m);
    register_FieldConstructorWithExcluded(m);
    register_FieldConstructorWithExcludedOnly(m);
    register_FieldConstructorWithParentComment(m);
    register_FieldConstructorsAllDefaults(m);
    register_FieldConstructorsCppSkip(m);
    register_FieldConstructorsInternal(m);
    register_FieldConstructorsInternalFields(m);
    register_FieldConstructorsNullableTypes(m);
    register_FieldConstructorsNullableTypesFoodType(m);
    register_FieldConstructorsNullableTypesStructWithParameters(m);
    register_FieldConstructorsParameterDefaults(m);
    register_FieldConstructorsPartialDefaults(m);
    register_FieldConstructorsSkipAllFields(m);
    register_FieldConstructorsSkipCpp(m);
    register_FieldConstructorsSkipDefault(m);
    register_FieldConstructorsWithLabels(m);
    register_FieldCustomConstructorsMix(m);
    register_ImmutableDefaultCtor(m);
    register_ImmutableNamelessCtor(m);
    register_ImmutableStructNoClash(m);
    register_ImmutableStructWithClash(m);
    register_MutableStructImmutableFields(m);
    register_MutableStructImmutableFieldsDefault(m);
    register_MutableStructImmutableFieldsNameless(m);
    register_MutableStructNoClash(m);
    register_OuterStructWithFieldConstructor(m);
    register_OuterStructWithFieldConstructorInnerStructWithDefaults(m);
}
