

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_Equatable(py::module_& module);
void register_EquatableClass(py::module_& module);
void register_EquatableInterface(py::module_& module);
void register_EquatableStructWithAccessors(py::module_& module);
void register_EquatableStructWithInternalFields(py::module_& module);
void register_ExternalEquatable(py::module_& module);
void register_NonEquatableClass(py::module_& module);
void register_NonEquatableInterface(py::module_& module);
void register_PointerEquatableClass(py::module_& module);
void register_SimpleEquatableStruct(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_Equatable(m);
    register_EquatableClass(m);
    register_EquatableInterface(m);
    register_EquatableStructWithAccessors(m);
    register_EquatableStructWithInternalFields(m);
    register_ExternalEquatable(m);
    register_NonEquatableClass(m);
    register_NonEquatableInterface(m);
    register_PointerEquatableClass(m);
    register_SimpleEquatableStruct(m);
}
