

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_Equatable(pybind11::module_& module);
void register_EquatableClass(pybind11::module_& module);
void register_EquatableInterface(pybind11::module_& module);
void register_EquatableStructWithAccessors(pybind11::module_& module);
void register_EquatableStructWithInternalFields(pybind11::module_& module);
void register_ExternalEquatable(pybind11::module_& module);
void register_NonEquatableClass(pybind11::module_& module);
void register_NonEquatableInterface(pybind11::module_& module);
void register_PointerEquatableClass(pybind11::module_& module);
void register_SimpleEquatableStruct(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_Equatable(m);
    register_EquatableClass(m);
    register_EquatableInterface(m);
    register_EquatableStructWithAccessors(m);
    register_EquatableStructWithInternalFields(m);
    register_ExternalEquatable(m);
    register_NonEquatableClass(m);
    register_NonEquatableInterface(m);
    register_PointerEquatableClass(m);
    register_SimpleEquatableStruct(m);
}
