

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_DeprecatedFields(py::module_& module);
void register_RouteUtils(py::module_& module);
void register_ScalarKeyframe(py::module_& module);
void register_ScalarKeyframeTrack(py::module_& module);
void register_StructA(py::module_& module);
void register_StructB(py::module_& module);
void register_StructWithConstMethod(py::module_& module);
void register_StructWithList(py::module_& module);
void register_StructWithMap(py::module_& module);
void register_StructWithSet(py::module_& module);
void register_Structs(py::module_& module);
void register_StructsInstance(py::module_& module);
void register_StructsQualifiedType(py::module_& module);
void register_StructsWithConstants(py::module_& module);
void register_StructsWithConstantsInterface(py::module_& module);
void register_StructsWithMethods(py::module_& module);
void register_StructsWithMethodsInterface(py::module_& module);
void register_TypeCollection(py::module_& module);
void register_ValidationUtils(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_DeprecatedFields(m);
    register_RouteUtils(m);
    register_ScalarKeyframe(m);
    register_ScalarKeyframeTrack(m);
    register_StructA(m);
    register_StructB(m);
    register_StructWithConstMethod(m);
    register_StructWithList(m);
    register_StructWithMap(m);
    register_StructWithSet(m);
    register_Structs(m);
    register_StructsInstance(m);
    register_StructsQualifiedType(m);
    register_StructsWithConstants(m);
    register_StructsWithConstantsInterface(m);
    register_StructsWithMethods(m);
    register_StructsWithMethodsInterface(m);
    register_TypeCollection(m);
    register_ValidationUtils(m);
}
