

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_fire_StructsQualifiedType(pybind11::module_& module);
void register_fire_StructsQualifiedTypeQualifiedType(pybind11::module_& module);
void register_smoke_DeprecatedFields(pybind11::module_& module);
void register_smoke_RouteUtils(pybind11::module_& module);
void register_smoke_RouteUtilsRouteType(pybind11::module_& module);
void register_smoke_ScalarKeyframe(pybind11::module_& module);
void register_smoke_ScalarKeyframeTrack(pybind11::module_& module);
void register_smoke_StructA(pybind11::module_& module);
void register_smoke_StructB(pybind11::module_& module);
void register_smoke_StructWithConstMethod(pybind11::module_& module);
void register_smoke_StructWithList(pybind11::module_& module);
void register_smoke_StructWithMap(pybind11::module_& module);
void register_smoke_StructWithSet(pybind11::module_& module);
void register_smoke_Structs(pybind11::module_& module);
void register_smoke_StructsAllTypesStruct(pybind11::module_& module);
void register_smoke_StructsDoubleNestingImmutableStruct(pybind11::module_& module);
void register_smoke_StructsFooBar(pybind11::module_& module);
void register_smoke_StructsImmutableStructWithCppAccessors(pybind11::module_& module);
void register_smoke_StructsInstance(pybind11::module_& module);
void register_smoke_StructsLine(pybind11::module_& module);
void register_smoke_StructsMutableStructWithCppAccessors(pybind11::module_& module);
void register_smoke_StructsNestingImmutableStruct(pybind11::module_& module);
void register_smoke_StructsPoint(pybind11::module_& module);
void register_smoke_StructsStructWithArrayOfImmutable(pybind11::module_& module);
void register_smoke_StructsWithConstants(pybind11::module_& module);
void register_smoke_StructsWithConstantsInterface(pybind11::module_& module);
void register_smoke_StructsWithConstantsInterfaceMultiRoute(pybind11::module_& module);
void register_smoke_StructsWithConstantsInterfaceStructWithConstantsOnly(pybind11::module_& module);
void register_smoke_StructsWithConstantsRoute(pybind11::module_& module);
void register_smoke_StructsWithMethods(pybind11::module_& module);
void register_smoke_StructsWithMethodsInterface(pybind11::module_& module);
void register_smoke_StructsWithMethodsInterfaceStructWithStaticMethodsOnly(pybind11::module_& module);
void register_smoke_StructsWithMethodsInterfaceVector3(pybind11::module_& module);
void register_smoke_StructsWithMethodsVector(pybind11::module_& module);
void register_smoke_TypeCollection(pybind11::module_& module);
void register_smoke_TypeCollectionAllTypesStruct(pybind11::module_& module);
void register_smoke_TypeCollectionLine(pybind11::module_& module);
void register_smoke_TypeCollectionPoint(pybind11::module_& module);
void register_smoke_ValidationUtils(pybind11::module_& module);
void register_smoke_ValidationUtilsValidation(pybind11::module_& module);
void register_smoke_ValidationUtilsValidationErrorCode(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_fire_StructsQualifiedType(m);
    register_fire_StructsQualifiedTypeQualifiedType(m);
    register_smoke_DeprecatedFields(m);
    register_smoke_RouteUtils(m);
    register_smoke_RouteUtilsRouteType(m);
    register_smoke_ScalarKeyframe(m);
    register_smoke_ScalarKeyframeTrack(m);
    register_smoke_StructA(m);
    register_smoke_StructB(m);
    register_smoke_StructWithConstMethod(m);
    register_smoke_StructWithList(m);
    register_smoke_StructWithMap(m);
    register_smoke_StructWithSet(m);
    register_smoke_Structs(m);
    register_smoke_StructsAllTypesStruct(m);
    register_smoke_StructsDoubleNestingImmutableStruct(m);
    register_smoke_StructsFooBar(m);
    register_smoke_StructsImmutableStructWithCppAccessors(m);
    register_smoke_StructsInstance(m);
    register_smoke_StructsLine(m);
    register_smoke_StructsMutableStructWithCppAccessors(m);
    register_smoke_StructsNestingImmutableStruct(m);
    register_smoke_StructsPoint(m);
    register_smoke_StructsStructWithArrayOfImmutable(m);
    register_smoke_StructsWithConstants(m);
    register_smoke_StructsWithConstantsInterface(m);
    register_smoke_StructsWithConstantsInterfaceMultiRoute(m);
    register_smoke_StructsWithConstantsInterfaceStructWithConstantsOnly(m);
    register_smoke_StructsWithConstantsRoute(m);
    register_smoke_StructsWithMethods(m);
    register_smoke_StructsWithMethodsInterface(m);
    register_smoke_StructsWithMethodsInterfaceStructWithStaticMethodsOnly(m);
    register_smoke_StructsWithMethodsInterfaceVector3(m);
    register_smoke_StructsWithMethodsVector(m);
    register_smoke_TypeCollection(m);
    register_smoke_TypeCollectionAllTypesStruct(m);
    register_smoke_TypeCollectionLine(m);
    register_smoke_TypeCollectionPoint(m);
    register_smoke_ValidationUtils(m);
    register_smoke_ValidationUtilsValidation(m);
    register_smoke_ValidationUtilsValidationErrorCode(m);
}
