

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_InternalClass(pybind11::module_& module);
void register_smoke_InternalInterfaceParent(pybind11::module_& module);
void register_smoke_InternalClassInherits(pybind11::module_& module);
void register_smoke_InternalClassWithFunctions(pybind11::module_& module);
void register_smoke_InternalClassWithStaticProperty(pybind11::module_& module);
void register_smoke_InternalInterface(pybind11::module_& module);
void register_smoke_InternalPropertyOnly(pybind11::module_& module);
void register_smoke_OuterClassWithInternalAttribute(pybind11::module_& module);
void register_smoke_OuterClassWithInternalAttributeClassNestedInInternalClass(pybind11::module_& module);
void register_smoke_OuterClassWithInternalAttributeStructNestedInInternalClass(pybind11::module_& module);
void register_smoke_OuterStructWithInternalAttribute(pybind11::module_& module);
void register_smoke_OuterStructWithInternalAttributeClassNestedInInternalStruct(pybind11::module_& module);
void register_smoke_OuterStructWithInternalAttributeStructNestedInInternalStruct(pybind11::module_& module);
void register_smoke_PublicClass(pybind11::module_& module);
void register_smoke_PublicClassInternalEnum(pybind11::module_& module);
void register_smoke_PublicClassInternalStruct(pybind11::module_& module);
void register_smoke_PublicClassPublicStruct(pybind11::module_& module);
void register_smoke_PublicClassPublicStructWithInternalDefaults(pybind11::module_& module);
void register_smoke_PublicInterface(pybind11::module_& module);
void register_smoke_PublicInterfaceInternalStruct(pybind11::module_& module);
void register_smoke_PublicStructWithInternalConstructors(pybind11::module_& module);
void register_smoke_PublicStructWithNonDefaultInternalField(pybind11::module_& module);
void register_smoke_PublicTypeCollection(pybind11::module_& module);
void register_smoke_PublicTypeCollectionInternalStruct(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_InternalClass(m);
    register_smoke_InternalInterfaceParent(m);
    register_smoke_InternalClassInherits(m);
    register_smoke_InternalClassWithFunctions(m);
    register_smoke_InternalClassWithStaticProperty(m);
    register_smoke_InternalInterface(m);
    register_smoke_InternalPropertyOnly(m);
    register_smoke_OuterClassWithInternalAttribute(m);
    register_smoke_OuterClassWithInternalAttributeClassNestedInInternalClass(m);
    register_smoke_OuterClassWithInternalAttributeStructNestedInInternalClass(m);
    register_smoke_OuterStructWithInternalAttribute(m);
    register_smoke_OuterStructWithInternalAttributeClassNestedInInternalStruct(m);
    register_smoke_OuterStructWithInternalAttributeStructNestedInInternalStruct(m);
    register_smoke_PublicClass(m);
    register_smoke_PublicClassInternalEnum(m);
    register_smoke_PublicClassInternalStruct(m);
    register_smoke_PublicClassPublicStruct(m);
    register_smoke_PublicClassPublicStructWithInternalDefaults(m);
    register_smoke_PublicInterface(m);
    register_smoke_PublicInterfaceInternalStruct(m);
    register_smoke_PublicStructWithInternalConstructors(m);
    register_smoke_PublicStructWithNonDefaultInternalField(m);
    register_smoke_PublicTypeCollection(m);
    register_smoke_PublicTypeCollectionInternalStruct(m);
}
