

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_ParentInterface(pybind11::module_& module);
void register_foobar_CrossPackageChildClass(pybind11::module_& module);
void register_foobar_CrossPackageChildInterface(pybind11::module_& module);
void register_smoke_ParentClass(pybind11::module_& module);
void register_smoke_ChildClassFromClass(pybind11::module_& module);
void register_smoke_ChildClassFromInterface(pybind11::module_& module);
void register_smoke_InterfaceWithOverloads(pybind11::module_& module);
void register_smoke_ChildClassNameClash(pybind11::module_& module);
void register_smoke_ParentInterfaceWithBool(pybind11::module_& module);
void register_smoke_ChildClassWithBool(pybind11::module_& module);
void register_smoke_ParentClassWithImports(pybind11::module_& module);
void register_smoke_ChildClassWithImports(pybind11::module_& module);
void register_smoke_ParentInterfaceWithIncludes(pybind11::module_& module);
void register_smoke_ChildClassWithIncludes(pybind11::module_& module);
void register_smoke_InterfaceWithLambda(pybind11::module_& module);
void register_smoke_ChildClassWithLambda(pybind11::module_& module);
void register_smoke_ChildInterface(pybind11::module_& module);
void register_smoke_ParentWithCustomConstructor(pybind11::module_& module);
void register_smoke_ChildWithCustomConstructor(pybind11::module_& module);
void register_smoke_ParentWithClassReferences(pybind11::module_& module);
void register_smoke_ChildWithParentClassReferences(pybind11::module_& module);
void register_smoke_ForwardDeclarationBug(pybind11::module_& module);
void register_smoke_GrandChildInterface(pybind11::module_& module);
void register_smoke_IncludableClass(pybind11::module_& module);
void register_smoke_IncludableEnum(pybind11::module_& module);
void register_smoke_IncludableStruct(pybind11::module_& module);
void register_smoke_InternalParent(pybind11::module_& module);
void register_smoke_InternalChild(pybind11::module_& module);
void register_smoke_ShouldNotInclude(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_ParentInterface(m);
    register_foobar_CrossPackageChildClass(m);
    register_foobar_CrossPackageChildInterface(m);
    register_smoke_ParentClass(m);
    register_smoke_ChildClassFromClass(m);
    register_smoke_ChildClassFromInterface(m);
    register_smoke_InterfaceWithOverloads(m);
    register_smoke_ChildClassNameClash(m);
    register_smoke_ParentInterfaceWithBool(m);
    register_smoke_ChildClassWithBool(m);
    register_smoke_ParentClassWithImports(m);
    register_smoke_ChildClassWithImports(m);
    register_smoke_ParentInterfaceWithIncludes(m);
    register_smoke_ChildClassWithIncludes(m);
    register_smoke_InterfaceWithLambda(m);
    register_smoke_ChildClassWithLambda(m);
    register_smoke_ChildInterface(m);
    register_smoke_ParentWithCustomConstructor(m);
    register_smoke_ChildWithCustomConstructor(m);
    register_smoke_ParentWithClassReferences(m);
    register_smoke_ChildWithParentClassReferences(m);
    register_smoke_ForwardDeclarationBug(m);
    register_smoke_GrandChildInterface(m);
    register_smoke_IncludableClass(m);
    register_smoke_IncludableEnum(m);
    register_smoke_IncludableStruct(m);
    register_smoke_InternalParent(m);
    register_smoke_InternalChild(m);
    register_smoke_ShouldNotInclude(m);
}
