

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_ChildClassFromClass(py::module_& module);
void register_ChildClassFromInterface(py::module_& module);
void register_ChildClassNameClash(py::module_& module);
void register_ChildClassWithBool(py::module_& module);
void register_ChildClassWithImports(py::module_& module);
void register_ChildClassWithIncludes(py::module_& module);
void register_ChildClassWithLambda(py::module_& module);
void register_ChildInterface(py::module_& module);
void register_ChildWithCustomConstructor(py::module_& module);
void register_ChildWithParentClassReferences(py::module_& module);
void register_CrossPackageChildClass(py::module_& module);
void register_CrossPackageChildInterface(py::module_& module);
void register_ForwardDeclarationBug(py::module_& module);
void register_GrandChildInterface(py::module_& module);
void register_IncludableClass(py::module_& module);
void register_IncludableEnum(py::module_& module);
void register_IncludableStruct(py::module_& module);
void register_InterfaceWithLambda(py::module_& module);
void register_InterfaceWithOverloads(py::module_& module);
void register_InternalChild(py::module_& module);
void register_InternalParent(py::module_& module);
void register_ParentClass(py::module_& module);
void register_ParentClassWithImports(py::module_& module);
void register_ParentInterface(py::module_& module);
void register_ParentInterfaceWithBool(py::module_& module);
void register_ParentInterfaceWithIncludes(py::module_& module);
void register_ParentWithClassReferences(py::module_& module);
void register_ParentWithCustomConstructor(py::module_& module);
void register_ShouldNotInclude(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_ChildClassFromClass(m);
    register_ChildClassFromInterface(m);
    register_ChildClassNameClash(m);
    register_ChildClassWithBool(m);
    register_ChildClassWithImports(m);
    register_ChildClassWithIncludes(m);
    register_ChildClassWithLambda(m);
    register_ChildInterface(m);
    register_ChildWithCustomConstructor(m);
    register_ChildWithParentClassReferences(m);
    register_CrossPackageChildClass(m);
    register_CrossPackageChildInterface(m);
    register_ForwardDeclarationBug(m);
    register_GrandChildInterface(m);
    register_IncludableClass(m);
    register_IncludableEnum(m);
    register_IncludableStruct(m);
    register_InterfaceWithLambda(m);
    register_InterfaceWithOverloads(m);
    register_InternalChild(m);
    register_InternalParent(m);
    register_ParentClass(m);
    register_ParentClassWithImports(m);
    register_ParentInterface(m);
    register_ParentInterfaceWithBool(m);
    register_ParentInterfaceWithIncludes(m);
    register_ParentWithClassReferences(m);
    register_ParentWithCustomConstructor(m);
    register_ShouldNotInclude(m);
}
