

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_Comments(py::module_& module);
void register_CommentsInterface(py::module_& module);
void register_CommentsLinks(py::module_& module);
void register_CommentsMarkdown(py::module_& module);
void register_CommentsTable(py::module_& module);
void register_CommentsTableLinks(py::module_& module);
void register_CommentsTypeCollection(py::module_& module);
void register_CtorLinks(py::module_& module);
void register_DeprecatedWithNoMessage(py::module_& module);
void register_DeprecationComments(py::module_& module);
void register_DeprecationCommentsOnly(py::module_& module);
void register_ExcludedComments(py::module_& module);
void register_ExcludedCommentsInterface(py::module_& module);
void register_ExcludedCommentsOnly(py::module_& module);
void register_InternalClassWithComments(py::module_& module);
void register_LambdaComments(py::module_& module);
void register_LongComments(py::module_& module);
void register_MapScene(py::module_& module);
void register_MultiLineComments(py::module_& module);
void register_PlatformComments(py::module_& module);
void register_PlatformCommentsLineBreaks(py::module_& module);
void register_UnicodeComments(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_Comments(m);
    register_CommentsInterface(m);
    register_CommentsLinks(m);
    register_CommentsMarkdown(m);
    register_CommentsTable(m);
    register_CommentsTableLinks(m);
    register_CommentsTypeCollection(m);
    register_CtorLinks(m);
    register_DeprecatedWithNoMessage(m);
    register_DeprecationComments(m);
    register_DeprecationCommentsOnly(m);
    register_ExcludedComments(m);
    register_ExcludedCommentsInterface(m);
    register_ExcludedCommentsOnly(m);
    register_InternalClassWithComments(m);
    register_LambdaComments(m);
    register_LongComments(m);
    register_MapScene(m);
    register_MultiLineComments(m);
    register_PlatformComments(m);
    register_PlatformCommentsLineBreaks(m);
    register_UnicodeComments(m);
}
