

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_Comments(pybind11::module_& module);
void register_smoke_CommentsInterface(pybind11::module_& module);
void register_smoke_CommentsInterfaceSomeEnum(pybind11::module_& module);
void register_smoke_CommentsInterfaceSomeStruct(pybind11::module_& module);
void register_smoke_CommentsLinks(pybind11::module_& module);
void register_smoke_CommentsLinksRandomStruct(pybind11::module_& module);
void register_smoke_CommentsMarkdown(pybind11::module_& module);
void register_smoke_CommentsTable(pybind11::module_& module);
void register_smoke_CommentsTableLinks(pybind11::module_& module);
void register_smoke_CommentsTypeCollection(pybind11::module_& module);
void register_smoke_CommentsTypeCollectionTypeCollectionEnum(pybind11::module_& module);
void register_smoke_CommentsTypeCollectionTypeCollectionStruct(pybind11::module_& module);
void register_smoke_CtorLinks(pybind11::module_& module);
void register_smoke_CtorLinksOverloadedCtors(pybind11::module_& module);
void register_smoke_CtorLinksSingleCtor(pybind11::module_& module);
void register_smoke_CtorLinksSingleCtorWithOneArgument(pybind11::module_& module);
void register_smoke_CtorLinksSingleCtorWithTwoArgument(pybind11::module_& module);
void register_smoke_DeprecatedWithNoMessage(pybind11::module_& module);
void register_smoke_DeprecationComments(pybind11::module_& module);
void register_smoke_DeprecationCommentsOnly(pybind11::module_& module);
void register_smoke_DeprecationCommentsOnlySomeEnum(pybind11::module_& module);
void register_smoke_DeprecationCommentsOnlySomeStruct(pybind11::module_& module);
void register_smoke_DeprecationCommentsSomeEnum(pybind11::module_& module);
void register_smoke_DeprecationCommentsSomeStruct(pybind11::module_& module);
void register_smoke_DeprecationCommentsSomethingWrong(pybind11::module_& module);
void register_smoke_ExcludedComments(pybind11::module_& module);
void register_smoke_ExcludedCommentsInterface(pybind11::module_& module);
void register_smoke_ExcludedCommentsOnly(pybind11::module_& module);
void register_smoke_ExcludedCommentsOnlySomeEnum(pybind11::module_& module);
void register_smoke_ExcludedCommentsOnlySomeStruct(pybind11::module_& module);
void register_smoke_ExcludedCommentsOnlySomethingWrong(pybind11::module_& module);
void register_smoke_ExcludedCommentsSomeEnum(pybind11::module_& module);
void register_smoke_ExcludedCommentsSomeStruct(pybind11::module_& module);
void register_smoke_ExcludedCommentsSomethingWrong(pybind11::module_& module);
void register_smoke_InternalClassWithComments(pybind11::module_& module);
void register_smoke_LambdaComments(pybind11::module_& module);
void register_smoke_LongComments(pybind11::module_& module);
void register_smoke_MapScene(pybind11::module_& module);
void register_smoke_MultiLineComments(pybind11::module_& module);
void register_smoke_PlatformComments(pybind11::module_& module);
void register_smoke_PlatformCommentsLineBreaks(pybind11::module_& module);
void register_smoke_PlatformCommentsSomeEnum(pybind11::module_& module);
void register_smoke_PlatformCommentsSomethingWrong(pybind11::module_& module);
void register_smoke_PlatformCommentssomething(pybind11::module_& module);
void register_smoke_UnicodeComments(pybind11::module_& module);
void register_smoke_commentsSomeEnum(pybind11::module_& module);
void register_smoke_commentsSomeStruct(pybind11::module_& module);
void register_smoke_commentsSomethingWrong(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_Comments(m);
    register_smoke_CommentsInterface(m);
    register_smoke_CommentsInterfaceSomeEnum(m);
    register_smoke_CommentsInterfaceSomeStruct(m);
    register_smoke_CommentsLinks(m);
    register_smoke_CommentsLinksRandomStruct(m);
    register_smoke_CommentsMarkdown(m);
    register_smoke_CommentsTable(m);
    register_smoke_CommentsTableLinks(m);
    register_smoke_CommentsTypeCollection(m);
    register_smoke_CommentsTypeCollectionTypeCollectionEnum(m);
    register_smoke_CommentsTypeCollectionTypeCollectionStruct(m);
    register_smoke_CtorLinks(m);
    register_smoke_CtorLinksOverloadedCtors(m);
    register_smoke_CtorLinksSingleCtor(m);
    register_smoke_CtorLinksSingleCtorWithOneArgument(m);
    register_smoke_CtorLinksSingleCtorWithTwoArgument(m);
    register_smoke_DeprecatedWithNoMessage(m);
    register_smoke_DeprecationComments(m);
    register_smoke_DeprecationCommentsOnly(m);
    register_smoke_DeprecationCommentsOnlySomeEnum(m);
    register_smoke_DeprecationCommentsOnlySomeStruct(m);
    register_smoke_DeprecationCommentsSomeEnum(m);
    register_smoke_DeprecationCommentsSomeStruct(m);
    register_smoke_DeprecationCommentsSomethingWrong(m);
    register_smoke_ExcludedComments(m);
    register_smoke_ExcludedCommentsInterface(m);
    register_smoke_ExcludedCommentsOnly(m);
    register_smoke_ExcludedCommentsOnlySomeEnum(m);
    register_smoke_ExcludedCommentsOnlySomeStruct(m);
    register_smoke_ExcludedCommentsOnlySomethingWrong(m);
    register_smoke_ExcludedCommentsSomeEnum(m);
    register_smoke_ExcludedCommentsSomeStruct(m);
    register_smoke_ExcludedCommentsSomethingWrong(m);
    register_smoke_InternalClassWithComments(m);
    register_smoke_LambdaComments(m);
    register_smoke_LongComments(m);
    register_smoke_MapScene(m);
    register_smoke_MultiLineComments(m);
    register_smoke_PlatformComments(m);
    register_smoke_PlatformCommentsLineBreaks(m);
    register_smoke_PlatformCommentsSomeEnum(m);
    register_smoke_PlatformCommentsSomethingWrong(m);
    register_smoke_PlatformCommentssomething(m);
    register_smoke_UnicodeComments(m);
    register_smoke_commentsSomeEnum(m);
    register_smoke_commentsSomeStruct(m);
    register_smoke_commentsSomethingWrong(m);
}
