

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_FreeEnum(pybind11::module_& module);
void register_smoke_FreeError(pybind11::module_& module);
void register_smoke_FreePoint(pybind11::module_& module);
void register_smoke_LevelOne(pybind11::module_& module);
void register_smoke_LevelOneLevelTwo(pybind11::module_& module);
void register_smoke_LevelOneLevelTwoLevelThree(pybind11::module_& module);
void register_smoke_LevelOneLevelTwoLevelThreeLevelFour(pybind11::module_& module);
void register_smoke_LevelOneLevelTwoLevelThreeLevelFourEnum(pybind11::module_& module);
void register_smoke_MyOuterClass(pybind11::module_& module);
void register_MyParentInterface(pybind11::module_& module);
void register_smoke_MyOuterClassMyNestedImplementation(pybind11::module_& module);
void register_smoke_MyParentInterface(pybind11::module_& module);
void register_smoke_NestedReferences(pybind11::module_& module);
void register_smoke_NestedReferencesNestedReferences(pybind11::module_& module);
void register_smoke_OuterClass(pybind11::module_& module);
void register_smoke_OuterClassInnerClass(pybind11::module_& module);
void register_smoke_OuterClassInnerInterface(pybind11::module_& module);
void register_ParentClass(pybind11::module_& module);
void register_smoke_OuterClassWithInheritance(pybind11::module_& module);
void register_smoke_OuterClassWithInheritanceInnerClass(pybind11::module_& module);
void register_smoke_OuterClassWithInheritanceInnerInterface(pybind11::module_& module);
void register_smoke_OuterInterface(pybind11::module_& module);
void register_smoke_OuterInterfaceInnerClass(pybind11::module_& module);
void register_smoke_OuterInterfaceInnerInterface(pybind11::module_& module);
void register_smoke_OuterStruct(pybind11::module_& module);
void register_smoke_OuterStructBuilder(pybind11::module_& module);
void register_smoke_OuterStructInnerClass(pybind11::module_& module);
void register_smoke_OuterStructInnerEnum(pybind11::module_& module);
void register_smoke_OuterStructInnerInterface(pybind11::module_& module);
void register_smoke_OuterStructInnerStruct(pybind11::module_& module);
void register_smoke_OuterStructInstantiation(pybind11::module_& module);
void register_smoke_ParentClass(pybind11::module_& module);
void register_smoke_UnusedTopLevelEnum(pybind11::module_& module);
void register_smoke_UnusedTopLevelPoint(pybind11::module_& module);
void register_smoke_UseFreeTypes(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_FreeEnum(m);
    register_smoke_FreeError(m);
    register_smoke_FreePoint(m);
    register_smoke_LevelOne(m);
    register_smoke_LevelOneLevelTwo(m);
    register_smoke_LevelOneLevelTwoLevelThree(m);
    register_smoke_LevelOneLevelTwoLevelThreeLevelFour(m);
    register_smoke_LevelOneLevelTwoLevelThreeLevelFourEnum(m);
    register_smoke_MyOuterClass(m);
    register_MyParentInterface(m);
    register_smoke_MyOuterClassMyNestedImplementation(m);
    register_smoke_MyParentInterface(m);
    register_smoke_NestedReferences(m);
    register_smoke_NestedReferencesNestedReferences(m);
    register_smoke_OuterClass(m);
    register_smoke_OuterClassInnerClass(m);
    register_smoke_OuterClassInnerInterface(m);
    register_ParentClass(m);
    register_smoke_OuterClassWithInheritance(m);
    register_smoke_OuterClassWithInheritanceInnerClass(m);
    register_smoke_OuterClassWithInheritanceInnerInterface(m);
    register_smoke_OuterInterface(m);
    register_smoke_OuterInterfaceInnerClass(m);
    register_smoke_OuterInterfaceInnerInterface(m);
    register_smoke_OuterStruct(m);
    register_smoke_OuterStructBuilder(m);
    register_smoke_OuterStructInnerClass(m);
    register_smoke_OuterStructInnerEnum(m);
    register_smoke_OuterStructInnerInterface(m);
    register_smoke_OuterStructInnerStruct(m);
    register_smoke_OuterStructInstantiation(m);
    register_smoke_ParentClass(m);
    register_smoke_UnusedTopLevelEnum(m);
    register_smoke_UnusedTopLevelPoint(m);
    register_smoke_UseFreeTypes(m);
}
