

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_FreeEnum(pybind11::module_& module);
void register_FreeError(pybind11::module_& module);
void register_FreePoint(pybind11::module_& module);
void register_LevelOne(pybind11::module_& module);
void register_MyOuterClass(pybind11::module_& module);
void register_MyParentInterface(pybind11::module_& module);
void register_NestedReferences(pybind11::module_& module);
void register_OuterClass(pybind11::module_& module);
void register_OuterClassWithInheritance(pybind11::module_& module);
void register_OuterInterface(pybind11::module_& module);
void register_OuterStruct(pybind11::module_& module);
void register_ParentClass(pybind11::module_& module);
void register_UnusedTopLevelEnum(pybind11::module_& module);
void register_UnusedTopLevelPoint(pybind11::module_& module);
void register_UseFreeTypes(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_FreeEnum(m);
    register_FreeError(m);
    register_FreePoint(m);
    register_LevelOne(m);
    register_MyOuterClass(m);
    register_MyParentInterface(m);
    register_NestedReferences(m);
    register_OuterClass(m);
    register_OuterClassWithInheritance(m);
    register_OuterInterface(m);
    register_OuterStruct(m);
    register_ParentClass(m);
    register_UnusedTopLevelEnum(m);
    register_UnusedTopLevelPoint(m);
    register_UseFreeTypes(m);
}
