

"""Base class for native-backed Python wrappers generated by Gluecodium."""

import atexit
import importlib
import inspect
import types
import weakref
from collections.abc import Callable
from datetime import date, datetime, timedelta
from typing import Any, Union, get_args, get_origin


def _unwrap(value: Any, type_hint: Any = Any) -> Any:
    if hasattr(value, "_native"):
        return value._native
    if value is None or type_hint is Any or type_hint is None:
        if isinstance(value, list):
            return [_unwrap(item) for item in value]
        if isinstance(value, (set, frozenset, tuple)):
            return type(value)(_unwrap(item) for item in value)
        if isinstance(value, dict):
            return {_unwrap(key): _unwrap(item) for key, item in value.items()}
        return value
    origin = get_origin(type_hint)
    args = get_args(type_hint)
    if origin is Callable:
        return _adapt_callable(value, args, to_native=True)
    if origin in (Union, types.UnionType):
        non_null_args = [arg for arg in args if arg is not type(None)]
        return _unwrap(value, non_null_args[0]) if non_null_args else value
    if origin is list:
        return [_unwrap(item, args[0]) for item in value]
    if origin is set:
        return {_unwrap(item, args[0]) for item in value}
    if origin is frozenset:
        return frozenset(_unwrap(item, args[0]) for item in value)
    if origin is tuple:
        item_hint = args[0]
        if len(args) > 1 and args[1] is not Ellipsis:
            return tuple(_unwrap(item, hint) for item, hint in zip(value, args))
        return tuple(_unwrap(item, item_hint) for item in value)
    if origin is frozenset:
        return frozenset(_unwrap(item, args[0]) for item in value)
    if origin is dict:
        return {
            _unwrap(key, args[0]): _unwrap(item, args[1]) for key, item in value.items()
        }
    return value


def _wrap(value: Any, type_hint: Any) -> Any:
    if value is None or type_hint is Any or type_hint is None:
        return value
    origin = get_origin(type_hint)
    args = get_args(type_hint)
    if origin is Callable:
        return _adapt_callable(value, args, to_native=False)
    if origin is list:
        return [_wrap(item, args[0]) for item in value]
    if origin is set:
        return {_hashable_key(_wrap(item, args[0])) for item in value}
    if origin is frozenset:
        return frozenset(_hashable_key(_wrap(item, args[0])) for item in value)
    if origin is tuple:
        item_hint = args[0]
        if len(args) > 1 and args[1] is not Ellipsis:
            return tuple(_wrap(item, hint) for item, hint in zip(value, args))
        return tuple(_wrap(item, item_hint) for item in value)
    if origin is dict:
        return {_hashable_key(_wrap(key, args[0])): _wrap(item, args[1]) for key, item in value.items()}
    if origin in (Union, types.UnionType):
        non_null_args = [arg for arg in args if arg is not type(None)]
        return _wrap(value, non_null_args[0]) if non_null_args else value
    if type_hint in (bool, int, float, str, bytes, date, datetime, timedelta):
        return value
    return _get_or_create_wrapper(value, type_hint)


_struct_key_types = weakref.WeakKeyDictionary()


def _struct_key(value, owner):
    key_type = _struct_key_types.get(owner)
    if key_type is None:
        class StructKey(owner):
            def __init__(self, source):
                if hasattr(self, "_StructKey__snapshot"):
                    raise AttributeError("Struct key snapshots are immutable")
                object.__setattr__(self, "_StructKey__snapshot", source._native.__gluecodium_copy__())

            @property
            def _native(self):
                # Never expose the stored value: getters and instance methods operate on copies.
                return self.__snapshot.__gluecodium_copy__()

            def __setattr__(self, name, value):
                raise AttributeError("Struct key snapshots are immutable")

            def __hash__(self):
                return self.__snapshot.__gluecodium_hash__()

            def as_key(self):
                return self

        key_type = StructKey
        _struct_key_types[owner] = key_type
    return value if isinstance(value, key_type) else key_type(value)


def _hashable_key(value):
    if isinstance(value, _NativeBase) and type(value).__hash__ is None and hasattr(value, "as_key"):
        return value.as_key()
    if isinstance(value, tuple):
        return tuple(_hashable_key(item) for item in value)
    if isinstance(value, frozenset):
        return frozenset(_hashable_key(item) for item in value)
    return value


def _callable_shape_matches(value, hint):
    if value is None or hint is Any:
        return True
    origin, args = get_origin(hint), get_args(hint)
    if origin in (Union, types.UnionType):
        return any(_callable_shape_matches(value, candidate) for candidate in args if candidate is not type(None))
    if origin is Callable:
        return callable(value)
    if origin is dict:
        return isinstance(value, dict) and all(
            _callable_shape_matches(key, args[0]) and _callable_shape_matches(item, args[1])
            for key, item in value.items()
        )
    if origin in (list, set, frozenset, tuple):
        if not isinstance(value, (list, set, frozenset, tuple)):
            return False
        if origin is tuple and len(args) > 1 and args[1] is not Ellipsis:
            return all(_callable_shape_matches(item, item_hint) for item, item_hint in zip(value, args))
        return all(_callable_shape_matches(item, args[0]) for item in value)
    # Resolve only the callable/non-callable distinction; pybind11 selects ordinary overloads.
    return not callable(value) or (isinstance(hint, type) and isinstance(value, hint))


def _contains_callable_value(value):
    if hasattr(value, "_native"):
        return False
    if callable(value):
        return True
    if isinstance(value, dict):
        return any(_contains_callable_value(key) or _contains_callable_value(item) for key, item in value.items())
    if isinstance(value, (list, set, frozenset, tuple)):
        return any(_contains_callable_value(item) for item in value)
    return False


def _unwrap_struct_args(args, kwargs, signatures, hints):
    def field_hint(name, value):
        # Constants may construct nested structs before their enclosing class exists.
        # Resolve lambda hints lazily, only when an actual callable needs conversion.
        return hints[name]() if name in hints and _contains_callable_value(value) else Any

    for fields in signatures:
        if len(args) + len(kwargs) != len(fields) or set(kwargs) != set(fields[len(args):]):
            continue
        values = list(zip(fields, args)) + list(kwargs.items())
        if any(name not in hints and _contains_callable_value(value) for name, value in values):
            continue
        if all(_callable_shape_matches(value, field_hint(name, value)) for name, value in values):
            return (
                [_unwrap(value, field_hint(name, value)) for name, value in zip(fields, args)],
                {name: _unwrap(value, field_hint(name, value)) for name, value in kwargs.items()},
            )
    # Leave invalid signatures to pybind11 for its usual argument diagnostics.
    return ([_unwrap(value) for value in args], {name: _unwrap(value) for name, value in kwargs.items()})


def _adapt_callable(callback, hints, *, to_native):
    if not callable(callback):
        return callback
    parameter_hints, return_hint = hints

    def adapted(*args):
        convert_args = _wrap if to_native else _unwrap
        convert_return = _unwrap if to_native else _wrap
        converted = [
            convert_args(value, parameter_hints[index]) if index < len(parameter_hints) else value
            for index, value in enumerate(args)
        ]
        return convert_return(callback(*converted), return_hint)

    return adapted


_generated_callback_functions = weakref.WeakSet()


def _mark_callback_base(cls):
    # Generated forwarding accessors are not user overrides, including borrowed base properties.
    for descriptor in cls.__dict__.values():
        functions = (descriptor.fget, descriptor.fset) if isinstance(descriptor, property) else (descriptor,)
        for function in functions:
            if isinstance(function, (staticmethod, classmethod)):
                function = function.__func__
            if inspect.isfunction(function):
                _generated_callback_functions.add(function)
    return cls


def _is_public_override(descriptor):
    function = descriptor.__func__ if isinstance(descriptor, (staticmethod, classmethod)) else descriptor
    return inspect.isfunction(function) and function not in _generated_callback_functions


def _install_callback_adapters(cls, owner, specifications):
    """Bridge genuine public overrides without changing ordinary Python method calls."""
    for name, bridge_name, kind, legacy_name, hints in specifications:
        descriptor = inspect.getattr_static(cls, name, None)
        original = inspect.getattr_static(owner, name, None)
        override = None
        if descriptor is not original:
            if kind == "method" and _is_public_override(descriptor):
                override = descriptor
            elif isinstance(descriptor, property):
                candidate = descriptor.fget if kind == "get" else descriptor.fset
                inherited = (original.fget if kind == "get" else original.fset) if isinstance(original, property) else None
                if _is_public_override(candidate) and candidate is not inherited:
                    override = candidate
        if override is None and legacy_name:
            descriptor = inspect.getattr_static(cls, legacy_name, None)
            if _is_public_override(descriptor):
                override = descriptor
        if override is None:
            continue

        def bridge(self, *args, _override=override, _hints=hints):
            parameters, return_type = _hints()
            values = [_wrap(value, hint) for value, hint in zip(args, parameters)]
            if isinstance(_override, staticmethod):
                result = _override.__func__(*values)
            elif isinstance(_override, classmethod):
                result = _override.__func__(type(self), *values)
            else:
                result = _override(self, *values)
            return _unwrap(result, return_type)

        setattr(cls, bridge_name, bridge)


# Wrapper cache: preserves referential equality across the C++ <-> Python boundary.
#
# When C++ returns a pointer/reference to an object that already has a Python wrapper, the same
# wrapper instance must be returned so that identity (``is``) is preserved. This mirrors the
# behaviour of Gluecodium's other language bindings (Dart InstanceCache, Swift WrapperCache).
#
# The cache is keyed on the C++ instance pointer (exposed via the ``__gluecodium_id__`` method
# registered on every pybind11 class/interface binding). Only class/interface types have this
# method; structs and enums are value types and are never cached.
_wrapper_cache = {}

# Clear the wrapper cache at interpreter exit to avoid segfaults during pybind11
# module unloading. The cache holds strong references to Python wrappers, which hold
# strong references to C++ shared_ptrs. Clearing the cache early ensures all C++ objects
# are released while the module is still fully functional.
atexit.register(_wrapper_cache.clear)


# Most-specific types first. Resolve public modules lazily to avoid import cycles.
_wrapper_types = [
    ("generated", "smoke_QuxInterface", "smoke.QuxInterface", "QuxInterface", False),
    ("generated", "smoke_QuxListener", "smoke.QuxListener", "QuxListener", False),
]


def _resolve_type(module_name, path):
    value = importlib.import_module(module_name)
    for part in path.split("."):
        value = getattr(value, part)
    return value


def _canonical_wrapper(native, wrapper_type):
    requested = (wrapper_type.__module__, wrapper_type.__qualname__)
    if any((module, path) == requested and narrow for _, _, module, path, narrow in _wrapper_types):
        return native, wrapper_type, True
    for native_module, native_path, module, path, narrow in _wrapper_types:
        if narrow:
            continue
        try:
            native_type = _resolve_type(native_module, native_path)
        except AttributeError:
            continue
        # Look on the type itself: an inherited downcast would select its base instead.
        downcast = native_type.__dict__.get("__gluecodium_downcast__")
        candidate = native if isinstance(native, native_type) else None
        if candidate is None and downcast is not None:
            candidate = getattr(native_type, "__gluecodium_downcast__")(native)
        if candidate is not None:
            return candidate, _resolve_type(module, path), False
    return native, wrapper_type, False


def _get_or_create_wrapper(native: Any, wrapper_type: Any) -> Any:
    if native is None:
        return None
    if get_origin(wrapper_type) in (Union, types.UnionType):
        return _wrap(native, wrapper_type)
    if hasattr(native, "__gluecodium_id__"):
        native, wrapper_type, narrow = _canonical_wrapper(native, wrapper_type)
        if isinstance(native, wrapper_type):
            return native
        key = (native.__gluecodium_id__(), wrapper_type if narrow else None)
        cached = _wrapper_cache.get(key)
        if cached is not None:
            return cached
        wrapper = wrapper_type(native)
        _wrapper_cache[key] = wrapper
        return wrapper
    if isinstance(native, wrapper_type):
        return native
    return wrapper_type(native)


class _NativeBase:
    """Wraps a native (C++/pybind11) object, exposing it through ``_native``."""

    def __init__(self, native: Any) -> None:
        self._native = native
