

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_ExposeClass(py::module_& module);
void register_ExposeEnum(py::module_& module);
void register_ExposeInterface(py::module_& module);
void register_ExposeInternalClass(py::module_& module);
void register_ExposeInternalEnum(py::module_& module);
void register_ExposeInternalInterface(py::module_& module);
void register_ExposeInternalNested(py::module_& module);
void register_ExposeInternalStruct(py::module_& module);
void register_ExposeStruct(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_ExposeClass(m);
    register_ExposeEnum(m);
    register_ExposeInterface(m);
    register_ExposeInternalClass(m);
    register_ExposeInternalEnum(m);
    register_ExposeInternalInterface(m);
    register_ExposeInternalNested(m);
    register_ExposeInternalStruct(m);
    register_ExposeStruct(m);
}
