

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_DartInternalClassWithInternalTypedef(pybind11::module_& module);
void register_SomeDartClassThatUsesInternal(pybind11::module_& module);
void register_SomeDartStructWithTypedefField(pybind11::module_& module);
void register_TypeCollection(pybind11::module_& module);
void register_TypeCollectionPoint(pybind11::module_& module);
void register_TypeCollectionStructHavingAliasFieldDefinedBelow(pybind11::module_& module);
void register_TypeDefs(pybind11::module_& module);
void register_TypeDefsStructHavingAliasFieldDefinedBelow(pybind11::module_& module);
void register_TypeDefsTestStruct(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_DartInternalClassWithInternalTypedef(m);
    register_SomeDartClassThatUsesInternal(m);
    register_SomeDartStructWithTypedefField(m);
    register_TypeCollection(m);
    register_TypeCollectionPoint(m);
    register_TypeCollectionStructHavingAliasFieldDefinedBelow(m);
    register_TypeDefs(m);
    register_TypeDefsStructHavingAliasFieldDefinedBelow(m);
    register_TypeDefsTestStruct(m);
}
