// Copyright (C) 2026 HERE Europe B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// License-Filename: LICENSE

#include "com/example/greeter/Greeter.h"
#include "com/example/greeter/GreetingListener.h"
#include "com/example/greeter/GreeterErrorCode.h"

#include <algorithm>
#include <sstream>
#include <system_error>

namespace {

// Concrete implementation of the generated `Greeter` abstract class. Gluecodium
// generates the abstract interface; the application must provide the body.
class GreeterImpl : public com::example::greeter::Greeter {
public:
    ::Return< ::std::string, ::std::error_code > greet(const ::std::string& name) override {
        if (name.empty()) {
            // The `throws GreeterError(GreeterErrorCode)` clause maps to
            // Return<string, std::error_code>; the generated caster raises it as
            // the Python `GreeterErrorError` exception. `make_error_code` is
            // generated by Gluecodium for the GreeterErrorCode enum.
            return ::com::example::greeter::make_error_code(
                ::com::example::greeter::GreeterErrorCode::EMPTY_NAME);
        }
        std::ostringstream out;
        out << "Hello, " << name << "!";
        ++greeting_count_;
        notify(name);
        return out.str();
    }

    void add_listener(const ::std::shared_ptr< ::com::example::greeter::GreetingListener >& listener) override {
        listener_ = listener;
    }

    int32_t get_greeting_count() const override { return greeting_count_; }
    void set_greeting_count(const int32_t value) override { greeting_count_ = value; }

private:
    void notify(const ::std::string& name) {
        if (listener_) {
            listener_->on_greeting("greeted: " + name);
        }
    }

    int32_t greeting_count_ = 0;
    ::std::shared_ptr< ::com::example::greeter::GreetingListener > listener_;
};

}  // namespace

namespace com {
namespace example {
namespace greeter {

::std::shared_ptr< Greeter > Greeter::create() {
    return ::std::make_shared< GreeterImpl >();
}

}  // namespace greeter
}  // namespace example
}  // namespace com

// Out-of-line definition of the pure-virtual interface method. Gluecodium
// generates the abstract `GreetingListener` with no body; providing one here
// gives the symbol a home so the extension module links and the trampoline's
// vtable resolves. The Python-side override is what actually runs.
namespace com {
namespace example {
namespace greeter {
void GreetingListener::on_greeting(const ::std::string&) {}
}  // namespace greeter
}  // namespace example
}  // namespace com

// The generated `GreetingListener.cpp` / `Greeter.cpp` already define the
// destructors (and therefore emit the vtable/typeinfo), so no further glue is
// needed here for linkage.
