// Copyright (C) 2026 HERE Europe B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// License-Filename: LICENSE

// Module entry point (Phase 6 of the Python generator plan). Gluecodium's
// `python` generator emits one `register_<Name>(py::module_&)` function per
// LIME type; this file aggregates them into a single CPython extension module.
//
// The module name ("greeter") must match the `-pythonmodule` option passed to
// Gluecodium and the name imported from Python.
//
// NOTE: At the current Phase 5 of the generator, the generated `register_*`
// functions for `class`/`interface` types are missing two pieces required to
// actually run:
//   * a `std::shared_ptr` holder for `class` types (so `create()` returning a
//     `shared_ptr` can be converted to Python), and
//   * a `py::init<>()` for `interface` types (so Python subclasses can be
//     instantiated as trampolines).
// Until Phase 6 lands, this file re-binds `Greeter` and `GreetingListener`
// with the correct holder + init. The struct (`Greeting`) and the exception
// translator (`GreeterErrorError`) are taken verbatim from the generator.

#include <pybind11/pybind11.h>

#include "com/example/greeter/Greeter.h"
#include "com/example/greeter/Greeting.h"
#include "com/example/greeter/GreetingListener.h"

// Forward declarations of the register_* functions generated by Gluecodium.
void register_Greeting(pybind11::module_& module);
void register_GreeterErrorError(pybind11::module_& module);

namespace py = pybind11;

// Corrected binding for the `Greeting` struct: adds `py::init<>` (and the
// two-argument constructor) so it can be instantiated from Python. The
// generated `register_Greeting` only exposes read/write fields.
void register_Greeting_fixed(py::module_& module) {
    py::class_<::com::example::greeter::Greeting>(module, "Greeting")
        .def(py::init<>())
        .def(py::init<const ::std::string&, int32_t>(), py::arg("name"), py::arg("count"))
        .def_readwrite("name", &::com::example::greeter::Greeting::name)
        .def_readwrite("count", &::com::example::greeter::Greeting::count);
}

// Corrected binding for the `Greeter` class: uses a `std::shared_ptr` holder so
// the `create()` factory (which returns `shared_ptr<Greeter>`) converts to
// Python, and so `add_listener` can accept a Python-implemented listener.
void register_Greeter_fixed(py::module_& module) {
    py::class_<::com::example::greeter::Greeter,
               ::std::shared_ptr<::com::example::greeter::Greeter>>(module, "Greeter")
        .def_static("create", &::com::example::greeter::Greeter::create)
        .def("greet", &::com::example::greeter::Greeter::greet, py::arg("name"))
        .def("add_listener", &::com::example::greeter::Greeter::add_listener, py::arg("listener"))
        .def_property("greeting_count",
                      py::overload_cast<>(&::com::example::greeter::Greeter::get_greeting_count, py::const_),
                      py::overload_cast<const int32_t>(&::com::example::greeter::Greeter::set_greeting_count));
}

// Corrected binding for the `GreetingListener` interface: adds `py::init<>()` so
// a Python subclass can be instantiated and passed back into C++ as a trampoline.
class GreetingListenerTrampoline : public ::com::example::greeter::GreetingListener {
public:
    using ::com::example::greeter::GreetingListener::GreetingListener;

    void on_greeting(const ::std::string& value) override {
        py::gil_scoped_acquire gil;
        PYBIND11_OVERRIDE(void, ::com::example::greeter::GreetingListener, on_greeting, value);
    }
};

void register_GreetingListener_fixed(py::module_& module) {
    py::class_<::com::example::greeter::GreetingListener,
               ::std::shared_ptr<::com::example::greeter::GreetingListener>,
               GreetingListenerTrampoline>(module, "GreetingListener")
        .def(py::init<>())
        .def("on_greeting", &::com::example::greeter::GreetingListener::on_greeting, py::arg("value"));
}

PYBIND11_MODULE(greeter, module) {
    module.doc() = "Python bindings for the Gluecodium-generated greeter API.";
    register_Greeting_fixed(module);          // Phase 6 glue (struct init)
    register_GreeterErrorError(module);       // generated (exception translator)
    register_Greeter_fixed(module);           // Phase 6 glue (class holder)
    register_GreetingListener_fixed(module);  // Phase 6 glue (interface init)
}
