

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_BasicTypes(pybind11::module_& module);
void register_smoke_CppRefReturnType(pybind11::module_& module);
void register_smoke_CppRefReturnTypeEnumBased(pybind11::module_& module);
void register_smoke_CppRefReturnTypeInternalError(pybind11::module_& module);
void register_smoke_CppRefReturnTypeSomeStruct(pybind11::module_& module);
void register_smoke_CppRefReturnTypeStruct(pybind11::module_& module);
void register_smoke_CppRefReturnTypeStructBased(pybind11::module_& module);
void register_smoke_StringsWithCstring(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_BasicTypes(m);
    register_smoke_CppRefReturnType(m);
    register_smoke_CppRefReturnTypeEnumBased(m);
    register_smoke_CppRefReturnTypeInternalError(m);
    register_smoke_CppRefReturnTypeSomeStruct(m);
    register_smoke_CppRefReturnTypeStruct(m);
    register_smoke_CppRefReturnTypeStructBased(m);
    register_smoke_StringsWithCstring(m);
}
