

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_AsyncClass(py::module_& module);
void register_AsyncError(py::module_& module);
void register_AsyncErrorCode(py::module_& module);
void register_AsyncRenamed(py::module_& module);
void register_AsyncStruct(py::module_& module);
void register_AsyncWithSkips(py::module_& module);
void register_ThrowMeError(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_AsyncClass(m);
    register_AsyncError(m);
    register_AsyncErrorCode(m);
    register_AsyncRenamed(m);
    register_AsyncStruct(m);
    register_AsyncWithSkips(m);
    register_ThrowMeError(m);
}
