# Copyright (C) 2026 HERE Europe B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

if(DEFINED includeguard_gluecodium_Js)
  return()
endif()
set(includeguard_gluecodium_Js ON)

cmake_minimum_required(VERSION 3.20)

include(${CMAKE_CURRENT_LIST_DIR}/gluecodium/details/CheckArguments.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/gluecodium/details/ListGeneratedFiles.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/gluecodium/details/ReadRequiredProperties.cmake)

#[=[.rst:
The JavaScript/WebAssembly Gluecodium module
---------------------------------------------

Provides :command:`gluecodium_target_js_sources`, which builds an Emscripten
module from the embind C++ sources generated by Gluecodium's ``js`` generator.
The whole target, including the C++ target passed to this function, must be
configured with the Emscripten toolchain.

#]=]

function(gluecodium_target_js_sources _target)
  set(_options)
  set(_single_args MODULE_NAME OUTPUT)
  cmake_parse_arguments(_args "${_options}" "${_single_args}" "" ${ARGN})
  gluecodium_check_no_unparsed_arguments(_args gluecodium_target_js_sources)

  gluecodium_read_required_properties(
    ${_target}
    GENERATORS _generators
    OUTPUT_MAIN_DIR _main_dir
    OUTPUT_UNITY_DIR _unity_dir)

  if(NOT js IN_LIST _generators)
    message(FATAL_ERROR "Target '${_target}' must use the 'js' generator")
  endif()

  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
    message(FATAL_ERROR
      "gluecodium_target_js_sources requires the Emscripten CMake toolchain; "
      "configure this project with emcmake")
  endif()

  gluecodium_list_generated_files(${_target} OUTPUT_JS _generated_js)
  if(NOT _generated_js)
    message(FATAL_ERROR "No JS sources were generated for target '${_target}'")
  endif()

  if(_args_MODULE_NAME)
    set(_module_name "${_args_MODULE_NAME}")
  else()
    get_target_property(_module_name ${_target} GLUECODIUM_JS_MODULE_NAME)
    if(NOT _module_name)
      set(_module_name "generated")
    endif()
  endif()

  set(_module_target "${_target}_js")
  add_executable(${_module_target} ${_generated_js})
  add_dependencies(${_module_target} ${_target}.gluecodium.generate)

  target_include_directories(${_module_target} PRIVATE
    "${_unity_dir}/cpp/include"
    "${_unity_dir}/js")
  get_target_property(_target_include_dirs ${_target} INCLUDE_DIRECTORIES)
  if(_target_include_dirs)
    target_include_directories(${_module_target} PRIVATE ${_target_include_dirs})
  endif()
  target_link_libraries(${_module_target} PRIVATE ${_target})

  target_compile_options(${_target} PRIVATE
    -pthread
    -fexceptions)
  target_compile_options(${_module_target} PRIVATE
    -pthread
    -fexceptions)
  target_link_options(${_module_target} PRIVATE
    -lembind
    -fexceptions
    -pthread
    -sPTHREAD_POOL_SIZE=4
    -sMODULARIZE=1
    -sEXPORT_ES6=1
    -sENVIRONMENT=web,node
    -sALLOW_MEMORY_GROWTH=1
    --no-entry)

  set_target_properties(${_module_target} PROPERTIES
    OUTPUT_NAME "${_module_name}"
    SUFFIX ".mjs")

  add_custom_command(TARGET ${_module_target} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory
      "${_main_dir}/js"
      "$<TARGET_FILE_DIR:${_module_target}>/js"
    COMMENT "Copy generated JavaScript package modules")

  if(_args_OUTPUT)
    set(${_args_OUTPUT} ${_module_target} PARENT_SCOPE)
  endif()
endfunction()