# Copyright (C) 2016-2025 HERE Europe B.V.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

if(DEFINED includeguard_gluecodium_Python)
  return()
endif()
set(includeguard_gluecodium_Python ON)

cmake_minimum_required(VERSION 3.10)

#[===========================================================================================[.rst:
The Python (pybind11) Gluecodium module
--------------------------------------

Provides :command:`gluecodium_target_python_sources`, which builds a CPython extension
module from the pybind11 sources generated by Gluecodium's ``python`` generator.

Unlike the other generators, the ``python`` generator does not emit a single "unity" source
file. Instead it writes a *directory* of files under ``<output>/unity/python/pybind11/``:

* one ``<pkg>_<Name>.cpp`` per top-level LIME type (each exposing a
  ``void register_<Name>(pybind11::module_&)``),
* the shared ``_return_caster.h`` / ``_wrapper_cache.h`` helpers,
* the ``_module_init.cpp`` ``PYBIND11_MODULE`` entry point that aggregates every
  ``register_*`` function.

Because ``python_add_library`` validates its source list at *configure* time, the pybind11
sources must already exist when CMake configures the extension target. There are two ways to
satisfy this:

1. Generate at configure time (the approach used by the sample project): invoke Gluecodium
   via ``execute_process`` before calling this function, so the ``.cpp`` files exist.
2. Generate at build time through ``gluecodium_generate``: in that case the generated files
   are produced by a custom command, so the glob below captures them on a *re-run* of CMake
   (after the first build populated the directory). A ``file(GLOB)`` is used so the list
   stays in sync with the LimeIDL input without manual maintenance.

#]===========================================================================================]

include(${CMAKE_CURRENT_LIST_DIR}/gluecodium/details/ReadRequiredProperties.cmake)

#[===========================================================================================[.rst:
.. command:: gluecodium_target_python_sources

Builds a CPython extension module from the pybind11 sources generated for ``<target>``.

  gluecodium_target_python_sources(<target>
    [MODULE_NAME <name>]        # Override the PYBIND11_MODULE name (defaults to the
                                # GLUECODIUM_PYTHON_MODULE_NAME target property, then "generated").
    [OUTPUT_DIR <dir>]          # The unity output directory that contains the generated
                                # python/pybind11/*.cpp sources. Required when <target> was not
                                # generated through gluecodium_generate (e.g. generated manually
                                # via execute_process); otherwise it is read from the target's
                                # GLUECODIUM_OUTPUT_UNITY_DIR property.
    [OUTPUT <module_target>]    # Optional variable to receive the created module target name.
    )

The function:

* locates ``pybind11`` (``find_package(pybind11 REQUIRED)``),
* globs the generated ``python/pybind11/*.cpp`` sources from the unity output dir,
* creates a ``python_add_library(<target>_python MODULE WITH_SOABI ...)`` extension module,
* links the host ``<target>`` (the C++ library with the generated abstract classes + runtime)
  and the pybind11 include directories,
* exposes the module target name through the ``OUTPUT`` variable (and as
  ``<target>_python``) so callers can add their own implementation sources or tests.

Example::

  add_library(my_lib SHARED)
  gluecodium_generate(my_lib GENERATORS cpp python)
  gluecodium_target_lime_sources(my_lib PUBLIC "lime/foo.lime")
  gluecodium_target_python_sources(my_lib OUTPUT my_python_module)
  target_sources(my_python_module PRIVATE "cpp/FooImpl.cpp")

#]===========================================================================================]
function(gluecodium_target_python_sources _target)
  set(_options)
  set(_single_args MODULE_NAME OUTPUT_DIR OUTPUT)
  set(_multi_args)
  cmake_parse_arguments(_args "${_options}" "${_single_args}" "${_multi_args}" ${ARGN})
  gluecodium_check_no_unparsed_arguments(_args gluecodium_target_python_sources)

  find_package(Python 3.8 COMPONENTS Interpreter Development.Module REQUIRED)
  find_package(pybind11 REQUIRED)

  # Resolve the unity output directory. Prefer an explicit OUTPUT_DIR; otherwise read the
  # GLUECODIUM_OUTPUT_UNITY_DIR property set by gluecodium_generate / gluecodium_add_generate_command.
  if(_args_OUTPUT_DIR)
    set(_unity_dir "${_args_OUTPUT_DIR}")
  else()
    gluecodium_read_required_properties(${_target} OUTPUT_UNITY_DIR _unity_dir)
  endif()

  # The python generator writes its pybind11 bindings under <unity_dir>/python/pybind11/.
  set(_pybind11_dir "${_unity_dir}/python/pybind11")
  file(GLOB _pybind11_sources "${_pybind11_dir}/*.cpp")

  if(NOT _args_MODULE_NAME)
    get_target_property(_module_name ${_target} GLUECODIUM_PYTHON_MODULE_NAME)
    if(NOT _module_name)
      set(_module_name "generated")
    endif()
  else()
    set(_module_name "${_args_MODULE_NAME}")
  endif()

  set(_module_target "${_target}_python")
  python_add_library(${_module_target} MODULE WITH_SOABI ${_pybind11_sources})
  # Python imports an extension module by *filename*, so the built .so must be named after the
  # PYBIND11_MODULE symbol (the module name), not after the CMake target. Set OUTPUT_NAME
  # accordingly (WITH_SOABI still appends the platform SOABI suffix).
  set_target_properties(${_module_target} PROPERTIES OUTPUT_NAME "${_module_name}")

  target_include_directories(${_module_target} PRIVATE
    "${_unity_dir}/python"          # generated python/ package (for _wrapper_cache.h etc.)
    "${_unity_dir}/cpp/include"     # generated C++ headers + runtime
    "${pybind11_INCLUDE_DIRS}"
    "${Python_INCLUDE_DIRS}")

  target_link_libraries(${_module_target} PRIVATE ${_target})

  if(_args_OUTPUT)
    set(${_args_OUTPUT} ${_module_target} PARENT_SCOPE)
  endif()
endfunction()
