

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_CalculationResult(pybind11::module_& module);
void register_Calculator(pybind11::module_& module);
void register_CalculatorListener(pybind11::module_& module);
void register_InterfaceWithStatic(pybind11::module_& module);
void register_InternalListener(pybind11::module_& module);
void register_ListenerInterface(pybind11::module_& module);
void register_ListenerWithNullable(pybind11::module_& module);
void register_ListenerWithProperties(pybind11::module_& module);
void register_ListenersWithReturnValues(pybind11::module_& module);
void register_TemperatureObserver(pybind11::module_& module);
void register_Thermometer(pybind11::module_& module);
void register_Weakling(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_CalculationResult(m);
    register_Calculator(m);
    register_CalculatorListener(m);
    register_InterfaceWithStatic(m);
    register_InternalListener(m);
    register_ListenerInterface(m);
    register_ListenerWithNullable(m);
    register_ListenerWithProperties(m);
    register_ListenersWithReturnValues(m);
    register_TemperatureObserver(m);
    register_Thermometer(m);
    register_Weakling(m);
}
