

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_CalculationResult(py::module_& module);
void register_Calculator(py::module_& module);
void register_CalculatorListener(py::module_& module);
void register_InterfaceWithStatic(py::module_& module);
void register_InternalListener(py::module_& module);
void register_ListenerInterface(py::module_& module);
void register_ListenerWithNullable(py::module_& module);
void register_ListenerWithProperties(py::module_& module);
void register_ListenersWithReturnValues(py::module_& module);
void register_TemperatureObserver(py::module_& module);
void register_Thermometer(py::module_& module);
void register_Weakling(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_CalculationResult(m);
    register_Calculator(m);
    register_CalculatorListener(m);
    register_InterfaceWithStatic(m);
    register_InternalListener(m);
    register_ListenerInterface(m);
    register_ListenerWithNullable(m);
    register_ListenerWithProperties(m);
    register_ListenersWithReturnValues(m);
    register_TemperatureObserver(m);
    register_Thermometer(m);
    register_Weakling(m);
}
