

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_CalculationResult(pybind11::module_& module);
void register_smoke_Calculator(pybind11::module_& module);
void register_smoke_CalculatorListener(pybind11::module_& module);
void register_smoke_CalculatorListenerResultStruct(pybind11::module_& module);
void register_smoke_InterfaceWithStatic(pybind11::module_& module);
void register_smoke_InternalListener(pybind11::module_& module);
void register_smoke_ListenerInterface(pybind11::module_& module);
void register_smoke_ListenerWithNullable(pybind11::module_& module);
void register_smoke_ListenerWithProperties(pybind11::module_& module);
void register_smoke_ListenerWithPropertiesResultEnum(pybind11::module_& module);
void register_smoke_ListenerWithPropertiesResultStruct(pybind11::module_& module);
void register_smoke_ListenersWithReturnValues(pybind11::module_& module);
void register_smoke_ListenersWithReturnValuesResultEnum(pybind11::module_& module);
void register_smoke_ListenersWithReturnValuesResultStruct(pybind11::module_& module);
void register_smoke_TemperatureObserver(pybind11::module_& module);
void register_smoke_Thermometer(pybind11::module_& module);
void register_smoke_ThermometerAnotherNotification(pybind11::module_& module);
void register_smoke_ThermometerNotification(pybind11::module_& module);
void register_smoke_ThermometerSomeThermometerErrorCode(pybind11::module_& module);
void register_smoke_Weakling(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_CalculationResult(m);
    register_smoke_Calculator(m);
    register_smoke_CalculatorListener(m);
    register_smoke_CalculatorListenerResultStruct(m);
    register_smoke_InterfaceWithStatic(m);
    register_smoke_InternalListener(m);
    register_smoke_ListenerInterface(m);
    register_smoke_ListenerWithNullable(m);
    register_smoke_ListenerWithProperties(m);
    register_smoke_ListenerWithPropertiesResultEnum(m);
    register_smoke_ListenerWithPropertiesResultStruct(m);
    register_smoke_ListenersWithReturnValues(m);
    register_smoke_ListenersWithReturnValuesResultEnum(m);
    register_smoke_ListenersWithReturnValuesResultStruct(m);
    register_smoke_TemperatureObserver(m);
    register_smoke_Thermometer(m);
    register_smoke_ThermometerAnotherNotification(m);
    register_smoke_ThermometerNotification(m);
    register_smoke_ThermometerSomeThermometerErrorCode(m);
    register_smoke_Weakling(m);
}
