

"""Base class for native-backed Python wrappers generated by Gluecodium."""

import atexit
import types
from collections.abc import Callable
from datetime import date, datetime, timedelta
from typing import Any, Union, get_args, get_origin


def _unwrap(value: Any, type_hint: Any = Any) -> Any:
    if hasattr(value, "_native"):
        return value._native
    if value is None or type_hint is Any or type_hint is None:
        if isinstance(value, list):
            return [_unwrap(item) for item in value]
        if isinstance(value, (set, frozenset, tuple)):
            return type(value)(_unwrap(item) for item in value)
        if isinstance(value, dict):
            return {_unwrap(key): _unwrap(item) for key, item in value.items()}
        return value
    origin = get_origin(type_hint)
    args = get_args(type_hint)
    if origin in (Union, types.UnionType):
        non_null_args = [arg for arg in args if arg is not type(None)]
        return _unwrap(value, non_null_args[0]) if non_null_args else value
    if origin is list:
        return [_unwrap(item, args[0]) for item in value]
    if origin is set:
        return {_unwrap(item, args[0]) for item in value}
    if origin is frozenset:
        return frozenset(_unwrap(item, args[0]) for item in value)
    if origin is tuple:
        item_hint = args[0]
        if len(args) > 1 and args[1] is not Ellipsis:
            return tuple(_unwrap(item, hint) for item, hint in zip(value, args))
        return tuple(_unwrap(item, item_hint) for item in value)
    if origin is frozenset:
        return frozenset(_unwrap(item, args[0]) for item in value)
    if origin is dict:
        return {
            _unwrap(key, args[0]): _unwrap(item, args[1]) for key, item in value.items()
        }
    return value


def _wrap(value: Any, type_hint: Any) -> Any:
    if value is None or type_hint is Any or type_hint is None:
        return value
    origin = get_origin(type_hint)
    args = get_args(type_hint)
    if origin is Callable:
        return value
    if origin is list:
        return [_wrap(item, args[0]) for item in value]
    if origin is set:
        return {_wrap(item, args[0]) for item in value}
    if origin is frozenset:
        return frozenset(_wrap(item, args[0]) for item in value)
    if origin is tuple:
        item_hint = args[0]
        if len(args) > 1 and args[1] is not Ellipsis:
            return tuple(_wrap(item, hint) for item, hint in zip(value, args))
        return tuple(_wrap(item, item_hint) for item in value)
    if origin is dict:
        return {_wrap(key, args[0]): _wrap(item, args[1]) for key, item in value.items()}
    if origin in (Union, types.UnionType):
        non_null_args = [arg for arg in args if arg is not type(None)]
        return _wrap(value, non_null_args[0]) if non_null_args else value
    if type_hint in (bool, int, float, str, bytes, date, datetime, timedelta):
        return value
    return _get_or_create_wrapper(value, type_hint)


# Wrapper cache: preserves referential equality across the C++ <-> Python boundary.
#
# When C++ returns a pointer/reference to an object that already has a Python wrapper, the same
# wrapper instance must be returned so that identity (``is``) is preserved. This mirrors the
# behaviour of Gluecodium's other language bindings (Dart InstanceCache, Swift WrapperCache).
#
# The cache is keyed on the C++ instance pointer (exposed via the ``__gluecodium_id__`` method
# registered on every pybind11 class/interface binding). Only class/interface types have this
# method; structs and enums are value types and are never cached.
_wrapper_cache = {}

# Clear the wrapper cache at interpreter exit to avoid segfaults during pybind11
# module unloading. The cache holds strong references to Python wrappers, which hold
# strong references to C++ shared_ptrs. Clearing the cache early ensures all C++ objects
# are released while the module is still fully functional.
atexit.register(_wrapper_cache.clear)


def _get_or_create_wrapper(native: Any, wrapper_type: Any) -> Any:
    if native is None:
        return None
    if hasattr(native, "__gluecodium_id__"):
        key = native.__gluecodium_id__()
        cached = _wrapper_cache.get(key)
        if cached is not None:
            return cached
        wrapper = wrapper_type(native)
        _wrapper_cache[key] = wrapper
        return wrapper
    return wrapper_type(native)


class _NativeBase:
    """Wraps a native (C++/pybind11) object, exposing it through ``_native``."""

    def __init__(self, native: Any) -> None:
        self._native = native
