

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_ChildClassFromClassOverloads(py::module_& module);
void register_ChildClassFromInterfaceOverloads(py::module_& module);
void register_ChildInterfaceOverloads(py::module_& module);
void register_JavaMethodOverloads(py::module_& module);
void register_KotlinMethodOverloads(py::module_& module);
void register_MethodOverloads(py::module_& module);
void register_NullableOverloads(py::module_& module);
void register_OverloadsWithComments(py::module_& module);
void register_ParentClass(py::module_& module);
void register_ParentInterface(py::module_& module);
void register_SkippedOverloads(py::module_& module);
void register_SpecialNames(py::module_& module);
void register_SpecialNamesInterface(py::module_& module);
void register_SwiftConstructorOverloads(py::module_& module);
void register_SwiftMethodOverloads(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_ChildClassFromClassOverloads(m);
    register_ChildClassFromInterfaceOverloads(m);
    register_ChildInterfaceOverloads(m);
    register_JavaMethodOverloads(m);
    register_KotlinMethodOverloads(m);
    register_MethodOverloads(m);
    register_NullableOverloads(m);
    register_OverloadsWithComments(m);
    register_ParentClass(m);
    register_ParentInterface(m);
    register_SkippedOverloads(m);
    register_SpecialNames(m);
    register_SpecialNamesInterface(m);
    register_SwiftConstructorOverloads(m);
    register_SwiftMethodOverloads(m);
}
