

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-top-level-element register_* functions generated by Gluecodium.
// Each top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this function
// registers the top-level type AND all nested types using nested py::class_ scopes. This module
// entry point aggregates them into a single CPython extension module. The `pybind11::` prefix
// is used here because the `py` namespace alias is introduced further below (after these
// declarations).
void register_smoke_ClassInStruct(pybind11::module_& module);
void register_smoke_DeclarationOrder(pybind11::module_& module);
void register_smoke_DeclarationOrderWithFunctions(pybind11::module_& module);
void register_smoke_InterfaceInInterface(pybind11::module_& module);
void register_smoke_OrderInClass(pybind11::module_& module);
void register_smoke_OrderInStruct(pybind11::module_& module);
void register_smoke_OrderInStructWithFunctions(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_ClassInStruct(m);
    register_smoke_DeclarationOrder(m);
    register_smoke_DeclarationOrderWithFunctions(m);
    register_smoke_InterfaceInInterface(m);
    register_smoke_OrderInClass(m);
    register_smoke_OrderInStruct(m);
    register_smoke_OrderInStructWithFunctions(m);
}
