

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_smoke_ClassInStruct(pybind11::module_& module);
void register_smoke_ClassInStructFooChecker(pybind11::module_& module);
void register_smoke_DeclarationOrder(pybind11::module_& module);
void register_smoke_DeclarationOrderMainStruct(pybind11::module_& module);
void register_smoke_DeclarationOrderNestedStruct(pybind11::module_& module);
void register_smoke_DeclarationOrderSomeEnum(pybind11::module_& module);
void register_smoke_DeclarationOrderWithFunctions(pybind11::module_& module);
void register_smoke_DeclarationOrderWithFunctionsFieldStruct(pybind11::module_& module);
void register_smoke_DeclarationOrderWithFunctionsFooBar(pybind11::module_& module);
void register_smoke_DeclarationOrderWithFunctionsMainStructWithFunctions(pybind11::module_& module);
void register_smoke_DeclarationOrderWithFunctionsParameterStruct(pybind11::module_& module);
void register_smoke_DeclarationOrderWithFunctionsReturnStruct(pybind11::module_& module);
void register_smoke_DeclarationOrderWithFunctionsThrownStruct(pybind11::module_& module);
void register_smoke_InterfaceInInterface(pybind11::module_& module);
void register_smoke_InterfaceInInterfaceFooChecker(pybind11::module_& module);
void register_smoke_OrderInClass(pybind11::module_& module);
void register_smoke_OrderInClassMainStruct(pybind11::module_& module);
void register_smoke_OrderInClassNestedStruct(pybind11::module_& module);
void register_smoke_OrderInClassSomeEnum(pybind11::module_& module);
void register_smoke_OrderInStruct(pybind11::module_& module);
void register_smoke_OrderInStructNestedStruct(pybind11::module_& module);
void register_smoke_OrderInStructSomeEnum(pybind11::module_& module);
void register_smoke_OrderInStructWithFunctions(pybind11::module_& module);
void register_smoke_OrderInStructWithFunctionsNestedStruct(pybind11::module_& module);
void register_smoke_OrderInStructWithFunctionsSomeEnum(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_smoke_ClassInStruct(m);
    register_smoke_ClassInStructFooChecker(m);
    register_smoke_DeclarationOrder(m);
    register_smoke_DeclarationOrderMainStruct(m);
    register_smoke_DeclarationOrderNestedStruct(m);
    register_smoke_DeclarationOrderSomeEnum(m);
    register_smoke_DeclarationOrderWithFunctions(m);
    register_smoke_DeclarationOrderWithFunctionsFieldStruct(m);
    register_smoke_DeclarationOrderWithFunctionsFooBar(m);
    register_smoke_DeclarationOrderWithFunctionsMainStructWithFunctions(m);
    register_smoke_DeclarationOrderWithFunctionsParameterStruct(m);
    register_smoke_DeclarationOrderWithFunctionsReturnStruct(m);
    register_smoke_DeclarationOrderWithFunctionsThrownStruct(m);
    register_smoke_InterfaceInInterface(m);
    register_smoke_InterfaceInInterfaceFooChecker(m);
    register_smoke_OrderInClass(m);
    register_smoke_OrderInClassMainStruct(m);
    register_smoke_OrderInClassNestedStruct(m);
    register_smoke_OrderInClassSomeEnum(m);
    register_smoke_OrderInStruct(m);
    register_smoke_OrderInStructNestedStruct(m);
    register_smoke_OrderInStructSomeEnum(m);
    register_smoke_OrderInStructWithFunctions(m);
    register_smoke_OrderInStructWithFunctionsNestedStruct(m);
    register_smoke_OrderInStructWithFunctionsSomeEnum(m);
}
