

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(py::module_&)` from its own translation unit; this module entry point
// aggregates them into a single CPython extension module.
void register_AmbiguousConstants(py::module_& module);
void register_AmbiguousConstants(py::module_& module);
void register_AmbiguousDefaults(py::module_& module);
void register_AmbiguousEnum(py::module_& module);
void register_AmbiguousEnum(py::module_& module);
void register_ConstantDefaults(py::module_& module);
void register_Enum1(py::module_& module);
void register_Enum2(py::module_& module);
void register_Enum3(py::module_& module);
void register_Enum4(py::module_& module);
void register_EnumCollectionDefaults(py::module_& module);
void register_EnumCollectionDefaultsExternal(py::module_& module);
void register_EnumDefaults(py::module_& module);
void register_EnumDefaultsExternal(py::module_& module);
void register_EnumWrapper(py::module_& module);
void register_EnumWrapperExternal(py::module_& module);
void register_ExternalEnum1(py::module_& module);
void register_ExternalEnum2(py::module_& module);
void register_ExternalEnum3(py::module_& module);
void register_ExternalEnum4(py::module_& module);
void register_FooBarEnum(py::module_& module);
void register_InternalEnumDefaults(py::module_& module);
void register_SomeStruct(py::module_& module);
void register_SomethingEnum(py::module_& module);
void register_StructConstants(py::module_& module);
void register_StructWithPosEnums(py::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_AmbiguousConstants(m);
    register_AmbiguousConstants(m);
    register_AmbiguousDefaults(m);
    register_AmbiguousEnum(m);
    register_AmbiguousEnum(m);
    register_ConstantDefaults(m);
    register_Enum1(m);
    register_Enum2(m);
    register_Enum3(m);
    register_Enum4(m);
    register_EnumCollectionDefaults(m);
    register_EnumCollectionDefaultsExternal(m);
    register_EnumDefaults(m);
    register_EnumDefaultsExternal(m);
    register_EnumWrapper(m);
    register_EnumWrapperExternal(m);
    register_ExternalEnum1(m);
    register_ExternalEnum2(m);
    register_ExternalEnum3(m);
    register_ExternalEnum4(m);
    register_FooBarEnum(m);
    register_InternalEnumDefaults(m);
    register_SomeStruct(m);
    register_SomethingEnum(m);
    register_StructConstants(m);
    register_StructWithPosEnums(m);
}
