

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-type register_* functions generated by Gluecodium. Each
// top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this module entry
// point aggregates them into a single CPython extension module. The `pybind11::` prefix is used
// here because the `py` namespace alias is introduced further below (after these declarations).
void register_AmbiguousConstants(pybind11::module_& module);
void register_AmbiguousConstants(pybind11::module_& module);
void register_AmbiguousDefaults(pybind11::module_& module);
void register_AmbiguousEnum(pybind11::module_& module);
void register_AmbiguousEnum(pybind11::module_& module);
void register_ConstantDefaults(pybind11::module_& module);
void register_Enum1(pybind11::module_& module);
void register_Enum2(pybind11::module_& module);
void register_Enum3(pybind11::module_& module);
void register_Enum4(pybind11::module_& module);
void register_EnumCollectionDefaults(pybind11::module_& module);
void register_EnumCollectionDefaultsExternal(pybind11::module_& module);
void register_EnumDefaults(pybind11::module_& module);
void register_EnumDefaultsExternal(pybind11::module_& module);
void register_EnumWrapper(pybind11::module_& module);
void register_EnumWrapperExternal(pybind11::module_& module);
void register_ExternalEnum1(pybind11::module_& module);
void register_ExternalEnum2(pybind11::module_& module);
void register_ExternalEnum3(pybind11::module_& module);
void register_ExternalEnum4(pybind11::module_& module);
void register_FooBarEnum(pybind11::module_& module);
void register_InternalEnumDefaults(pybind11::module_& module);
void register_SomeStruct(pybind11::module_& module);
void register_SomethingEnum(pybind11::module_& module);
void register_StructConstants(pybind11::module_& module);
void register_StructWithPosEnums(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_AmbiguousConstants(m);
    register_AmbiguousConstants(m);
    register_AmbiguousDefaults(m);
    register_AmbiguousEnum(m);
    register_AmbiguousEnum(m);
    register_ConstantDefaults(m);
    register_Enum1(m);
    register_Enum2(m);
    register_Enum3(m);
    register_Enum4(m);
    register_EnumCollectionDefaults(m);
    register_EnumCollectionDefaultsExternal(m);
    register_EnumDefaults(m);
    register_EnumDefaultsExternal(m);
    register_EnumWrapper(m);
    register_EnumWrapperExternal(m);
    register_ExternalEnum1(m);
    register_ExternalEnum2(m);
    register_ExternalEnum3(m);
    register_ExternalEnum4(m);
    register_FooBarEnum(m);
    register_InternalEnumDefaults(m);
    register_SomeStruct(m);
    register_SomethingEnum(m);
    register_StructConstants(m);
    register_StructWithPosEnums(m);
}
