

#include <pybind11/pybind11.h>

#include "_wrapper_cache.h"
#include "_return_caster.h"

// Forward declarations of the per-top-level-element register_* functions generated by Gluecodium.
// Each top-level LIME type (except type aliases and lambdas, which need no binding) emits one
// `void register_<Name>(pybind11::module_&)` from its own translation unit; this function
// registers the top-level type AND all nested types using nested py::class_ scopes. This module
// entry point aggregates them into a single CPython extension module. The `pybind11::` prefix
// is used here because the `py` namespace alias is introduced further below (after these
// declarations).
void register_fire_AmbiguousConstants(pybind11::module_& module);
void register_fire_AmbiguousEnum(pybind11::module_& module);
void register_fire_Enum1(pybind11::module_& module);
void register_fire_Enum2(pybind11::module_& module);
void register_fire_Enum3(pybind11::module_& module);
void register_fire_Enum4(pybind11::module_& module);
void register_fire_ExternalEnum1(pybind11::module_& module);
void register_fire_ExternalEnum2(pybind11::module_& module);
void register_fire_ExternalEnum3(pybind11::module_& module);
void register_fire_ExternalEnum4(pybind11::module_& module);
void register_fire_SomeStruct(pybind11::module_& module);
void register_fire_StructConstants(pybind11::module_& module);
void register_smoke_AmbiguousConstants(pybind11::module_& module);
void register_smoke_AmbiguousDefaults(pybind11::module_& module);
void register_smoke_AmbiguousEnum(pybind11::module_& module);
void register_smoke_ConstantDefaults(pybind11::module_& module);
void register_smoke_EnumCollectionDefaults(pybind11::module_& module);
void register_smoke_EnumCollectionDefaultsExternal(pybind11::module_& module);
void register_smoke_EnumDefaults(pybind11::module_& module);
void register_smoke_EnumDefaultsExternal(pybind11::module_& module);
void register_smoke_EnumWrapper(pybind11::module_& module);
void register_smoke_EnumWrapperExternal(pybind11::module_& module);
void register_smoke_FooBarEnum(pybind11::module_& module);
void register_smoke_InternalEnumDefaults(pybind11::module_& module);
void register_smoke_SomethingEnum(pybind11::module_& module);
void register_smoke_StructWithPosEnums(pybind11::module_& module);

// pybind11 3.x no longer provides the `py` namespace alias by default.
namespace py = pybind11;

PYBIND11_MODULE(generated, m) {
    m.doc() = "Generated Python bindings for the 'generated' extension module.";

    register_fire_AmbiguousConstants(m);
    register_fire_AmbiguousEnum(m);
    register_fire_Enum1(m);
    register_fire_Enum2(m);
    register_fire_Enum3(m);
    register_fire_Enum4(m);
    register_fire_ExternalEnum1(m);
    register_fire_ExternalEnum2(m);
    register_fire_ExternalEnum3(m);
    register_fire_ExternalEnum4(m);
    register_fire_SomeStruct(m);
    register_fire_StructConstants(m);
    register_smoke_AmbiguousConstants(m);
    register_smoke_AmbiguousDefaults(m);
    register_smoke_AmbiguousEnum(m);
    register_smoke_ConstantDefaults(m);
    register_smoke_EnumCollectionDefaults(m);
    register_smoke_EnumCollectionDefaultsExternal(m);
    register_smoke_EnumDefaults(m);
    register_smoke_EnumDefaultsExternal(m);
    register_smoke_EnumWrapper(m);
    register_smoke_EnumWrapperExternal(m);
    register_smoke_FooBarEnum(m);
    register_smoke_InternalEnumDefaults(m);
    register_smoke_SomethingEnum(m);
    register_smoke_StructWithPosEnums(m);
}
