

"""Base class for native-backed Python wrappers generated by Gluecodium."""

from typing import Any


class _NativeBase:
    """Wraps a native (C++/pybind11) object, exposing it through ``_native``."""

    def __init__(self, native: Any) -> None:
        self._native = native
